export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська" },
] as const;

export type LanguageCode = (typeof SUPPORTED_LANGUAGES)[number]["code"];

export const DEFAULT_LANGUAGE: LanguageCode = "en";

export interface Translations {
  welcomeTitle: string;
  selectLevelSubtitle: string;
  currentLevelSubtitle: string;
  selectNewLevel: string;
  selectLanguage: string;
  appTitle: string;
  greeting: string;
  greetingSubtitle: string;
  placeholder: string;
  changeLevel: string;
  disclaimer: string;
  progress: string;
  newChat: string;
  conversations: string;
  help: string;
  history: string;
  settings: string;
  you: string;
  tutor: string;
  theme: string;
  systemMode: string;
  lightMode: string;
  darkMode: string;
  language: string;
  helpCenter: string;
  privacy: string;
  levelA1: string;
  levelA1Desc: string;
  levelA2: string;
  levelA2Desc: string;
  levelB1: string;
  levelB1Desc: string;
  levelB2: string;
  levelB2Desc: string;
  levelC1: string;
  levelC1Desc: string;
  levelC2: string;
  levelC2Desc: string;
  suggestionStart: string;
  suggestionV2: string;
  suggestionGrammar: string;
  suggestionTask: string;
  jumpToBottom: string;
  back: string;
  errorTitle: string;
  errorMessage: string;
  refresh: string;
  syncing: string;
  syncError: string;
  pendingChanges: string;
  login: string;
  signupForFree: string;
  account: string;
}

const shared: Omit<
  Translations,
  | "welcomeTitle"
  | "selectLevelSubtitle"
  | "currentLevelSubtitle"
  | "selectNewLevel"
  | "selectLanguage"
> = {
  appTitle: "Norwegian Learning",
  greeting: "Hello!",
  greetingSubtitle: "How can I help you learn Norwegian today?",
  placeholder: "Write in Norwegian here...",
  changeLevel: "Change Level",
  disclaimer:
    "Norwegian Learning may display inaccurate information, so double-check the responses.",
  progress: "Progress",
  newChat: "New Chat",
  conversations: "Conversations",
  help: "Help",
  history: "History",
  settings: "Settings",
  you: "You",
  tutor: "Tutor",
  theme: "Theme",
  systemMode: "System",
  lightMode: "Light",
  darkMode: "Dark",
  language: "Language",
  helpCenter: "Help Center",
  privacy: "Privacy",
  levelA1: "Beginner",
  levelA1Desc: "Basic survival phrases and simple sentences",
  levelA2: "Elementary",
  levelA2Desc: "Simple everyday conversations",
  levelB1: "Intermediate",
  levelB1Desc: "Clear communication on familiar topics",
  levelB2: "Upper Intermediate",
  levelB2Desc: "Fluent argumentation and complex topics",
  levelC1: "Advanced",
  levelC1Desc: "Fluent and spontaneous communication",
  levelC2: "Proficient",
  levelC2Desc: "Near-native proficiency",
  suggestionStart: "Hei, jeg heter...",
  suggestionV2: "Forklar V2-regelen",
  suggestionGrammar: "Hjelp meg med grammatikk",
  suggestionTask: "Gi meg en oppgave",
  jumpToBottom: "Jump to bottom",
  back: "Back",
  errorTitle: "Something went wrong",
  errorMessage: "Please refresh the page or try again later.",
  refresh: "Refresh Page",
  syncing: "Syncing...",
  syncError: "Sync error",
  pendingChanges: "pending changes",
  login: "Log in",
  signupForFree: "Sign up for free",
  account: "Account",
};

const translations: Record<LanguageCode, Translations> = {
  en: {
    welcomeTitle: "Welcome to Norwegian Learning!",
    selectLevelSubtitle: "Select your current CEFR level to begin",
    currentLevelSubtitle:
      "Your current level: {level}. Select a new level to change.",
    selectNewLevel: "Select a new level to change",
    selectLanguage: "Select Language",
    ...shared,
  },
  no: {
    welcomeTitle: "Velkommen til Norsk Læring!",
    selectLevelSubtitle: "Velg ditt nåværende CEFR-nivå for å begynne",
    currentLevelSubtitle:
      "Ditt nåværende nivå: {level}. Velg et nytt nivå for å endre.",
    selectNewLevel: "Velg et nytt nivå for å endre",
    selectLanguage: "Velg språk",
    appTitle: "Norsk Læring",
    greeting: "Hei!",
    greetingSubtitle: "Hvordan kan jeg hjelpe deg med å lære norsk i dag?",
    placeholder: "Skriv på norsk her...",
    changeLevel: "Endre Nivå",
    disclaimer:
      "Norsk Læring kan vise unøyaktig informasjon, så dobbeltsjekk svarene.",
    progress: "Framgang",
    newChat: "Ny Samtale",
    conversations: "Samtaler",
    help: "Hjelp",
    history: "Historikk",
    settings: "Innstillinger",
    you: "Deg",
    tutor: "Veileder",
    theme: "Tema",
    systemMode: "System",
    lightMode: "Lys",
    darkMode: "Mørk",
    language: "Språk",
    helpCenter: "Hjelpesenter",
    privacy: "Personvern",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Gå til bunn",
    back: "Tilbake",
    errorTitle: "Noe gikk galt",
    errorMessage: "Vennligst oppdater siden eller prøv igjen senere.",
    refresh: "Oppdater side",
    syncing: "Synkroniserer...",
    syncError: "Synkroniseringsfeil",
    pendingChanges: "ventende endringer",
    login: "Logg inn",
    signupForFree: "Registrer deg gratis",
    account: "Konto",
    levelA1: "Nybegynner",
    levelA1Desc: "Grunnleggende fraser og introduksjoner",
    levelA2: "Elementær",
    levelA2Desc: "Enkle hverdagslige samtaler",
    levelB1: "Mellomnivå",
    levelB1Desc: "Klare kommunikasjon om kjente emner",
    levelB2: "Øvre mellomnivå",
    levelB2Desc: "Selvsikker argumentasjon og diskusjoner",
    levelC1: "Avansert",
    levelC1Desc: "Flytende og spontan kommunikasjon",
    levelC2: "Kompetent",
    levelC2Desc: "Nær morsmålsnivå",
  },
  de: {
    welcomeTitle: "Willkommen beim Norwegischlernen!",
    selectLevelSubtitle: "Wählen Sie Ihr aktuelles GER-Niveau, um zu beginnen",
    currentLevelSubtitle:
      "Ihr aktuelles Niveau: {level}. Wählen Sie ein neues Niveau zum Ändern.",
    selectNewLevel: "Neues Niveau auswählen",
    selectLanguage: "Sprache auswählen",
    appTitle: "Norwegisch lernen",
    greeting: "Hallo!",
    greetingSubtitle: "Wie kann ich Ihnen heute beim Norwegischlernen helfen?",
    placeholder: "Schreiben Sie hier auf Norwegisch...",
    changeLevel: "Niveau ändern",
    disclaimer:
      "Norwegisch lernen kann ungenaue Informationen anzeigen, bitte überprüfen Sie die Antworten.",
    progress: "Fortschritt",
    newChat: "Neuer Chat",
    conversations: "Unterhaltungen",
    help: "Hilfe",
    history: "Verlauf",
    settings: "Einstellungen",
    you: "Sie",
    tutor: "Tutor",
    theme: "Design",
    systemMode: "System",
    lightMode: "Hell",
    darkMode: "Dunkel",
    language: "Sprache",
    helpCenter: "Hilfezentrum",
    privacy: "Datenschutz",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Zum Ende springen",
    back: "Zurück",
    errorTitle: "Etwas ist schief gelaufen",
    errorMessage: "Bitte aktualisieren Sie die Seite oder versuchen Sie es später erneut.",
    refresh: "Seite aktualisieren",
    syncing: "Synchronisierung...",
    syncError: "Synchronisierungsfehler",
    pendingChanges: "ausstehende Änderungen",
    login: "Anmelden",
    signupForFree: "Kostenlos registrieren",
    account: "Konto",
    levelA1: "Anfänger",
    levelA1Desc: "Grundlegende Phrasen und Einführungen",
    levelA2: "Elementar",
    levelA2Desc: "Einfache alltägliche Gespräche",
    levelB1: "Mittelstufe",
    levelB1Desc: "Klare Kommunikation über vertraute Themen",
    levelB2: "Obere Mittelstufe",
    levelB2Desc: "Selbstbewusste Argumentation und Diskussionen",
    levelC1: "Fortgeschritten",
    levelC1Desc: "Fließende und spontane Kommunikation",
    levelC2: "Kompetent",
    levelC2Desc: "Nahezu muttersprachliches Niveau",
  },
  fr: {
    welcomeTitle: "Bienvenue à l'apprentissage du norvégien !",
    selectLevelSubtitle:
      "Sélectionnez votre niveau CECR actuel pour commencer",
    currentLevelSubtitle:
      "Votre niveau actuel : {level}. Sélectionnez un nouveau niveau pour changer.",
    selectNewLevel: "Sélectionner un nouveau niveau",
    selectLanguage: "Sélectionner la langue",
    appTitle: "Apprentissage du Norvégien",
    greeting: "Bonjour !",
    greetingSubtitle: "Comment puis-je vous aider à apprendre le norvégien aujourd'hui ?",
    placeholder: "Écrivez en norvégien ici...",
    changeLevel: "Changer de Niveau",
    disclaimer:
      "L'Apprentissage du Norvégien peut afficher des informations inexactes, veuillez vérifier les réponses.",
    progress: "Progrès",
    newChat: "Nouvelle Conversation",
    conversations: "Conversations",
    help: "Aide",
    history: "Historique",
    settings: "Paramètres",
    you: "Vous",
    tutor: "Tuteur",
    theme: "Thème",
    systemMode: "Système",
    lightMode: "Clair",
    darkMode: "Sombre",
    language: "Langue",
    helpCenter: "Centre d'Aide",
    privacy: "Confidentialité",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Aller en bas",
    back: "Retour",
    errorTitle: "Une erreur s'est produite",
    errorMessage: "Veuillez actualiser la page ou réessayer plus tard.",
    refresh: "Actualiser la page",
    syncing: "Synchronisation...",
    syncError: "Erreur de synchronisation",
    pendingChanges: "modifications en attente",
    login: "Se connecter",
    signupForFree: "S'inscrire gratuitement",
    account: "Compte",
    levelA1: "Débutant",
    levelA1Desc: "Phrases de base et présentations",
    levelA2: "Élémentaire",
    levelA2Desc: "Conversations quotidiennes simples",
    levelB1: "Intermédiaire",
    levelB1Desc: "Communication claire sur des sujets familiers",
    levelB2: "Intermédiaire supérieur",
    levelB2Desc: "Argumentation confiante et discussions",
    levelC1: "Avancé",
    levelC1Desc: "Communication fluide et spontanée",
    levelC2: "Compétent",
    levelC2Desc: "Maîtrise quasi-natale",
  },
  es: {
    welcomeTitle: "¡Bienvenido al aprendizaje de noruego!",
    selectLevelSubtitle:
      "Seleccione su nivel actual del MCER para comenzar",
    currentLevelSubtitle:
      "Su nivel actual: {level}. Seleccione un nuevo nivel para cambiar.",
    selectNewLevel: "Seleccionar un nuevo nivel",
    selectLanguage: "Seleccionar idioma",
    appTitle: "Aprendizaje de Noruego",
    greeting: "¡Hola!",
    greetingSubtitle: "¿Cómo puedo ayudarte a aprender noruego hoy?",
    placeholder: "Escribe en noruego aquí...",
    changeLevel: "Cambiar Nivel",
    disclaimer:
      "El Aprendizaje de Noruego puede mostrar información inexacta, verifica las respuestas.",
    progress: "Progreso",
    newChat: "Nueva Conversación",
    conversations: "Conversaciones",
    help: "Ayuda",
    history: "Historial",
    settings: "Configuración",
    you: "Tú",
    tutor: "Tutor",
    theme: "Tema",
    systemMode: "Sistema",
    lightMode: "Claro",
    darkMode: "Oscuro",
    language: "Idioma",
    helpCenter: "Centro de Ayuda",
    privacy: "Privacidad",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Ir al final",
    back: "Volver",
    errorTitle: "Algo salió mal",
    errorMessage: "Por favor, actualice la página o intente nuevamente más tarde.",
    refresh: "Actualizar página",
    syncing: "Sincronizando...",
    syncError: "Error de sincronización",
    pendingChanges: "cambios pendientes",
    login: "Iniciar sesión",
    signupForFree: "Regístrate gratis",
    account: "Cuenta",
    levelA1: "Principiante",
    levelA1Desc: "Frases básicas y presentaciones",
    levelA2: "Elemental",
    levelA2Desc: "Conversaciones cotidianas simples",
    levelB1: "Intermedio",
    levelB1Desc: "Comunicación clara sobre temas familiares",
    levelB2: "Intermedio superior",
    levelB2Desc: "Argumentación segura y debates",
    levelC1: "Avanzado",
    levelC1Desc: "Comunicación fluida y espontánea",
    levelC2: "Competente",
    levelC2Desc: "Dominio casi nativo",
  },
  it: {
    welcomeTitle: "Benvenuti all'apprendimento del norvegese!",
    selectLevelSubtitle:
      "Seleziona il tuo livello QCER attuale per iniziare",
    currentLevelSubtitle:
      "Il tuo livello attuale: {level}. Seleziona un nuovo livello per cambiare.",
    selectNewLevel: "Seleziona un nuovo livello",
    selectLanguage: "Seleziona lingua",
    appTitle: "Apprendimento del Norvegese",
    greeting: "Ciao!",
    greetingSubtitle: "Come posso aiutarti a imparare il norvegese oggi?",
    placeholder: "Scrivi in norvegese qui...",
    changeLevel: "Cambia Livello",
    disclaimer:
      "L'Apprendimento del Norvegese può mostrare informazioni inaccurate, verifica le risposte.",
    progress: "Progresso",
    newChat: "Nuova Conversazione",
    conversations: "Conversazioni",
    help: "Aiuto",
    history: "Cronologia",
    settings: "Impostazioni",
    you: "Tu",
    tutor: "Tutor",
    theme: "Tema",
    systemMode: "Sistema",
    lightMode: "Chiaro",
    darkMode: "Scuro",
    language: "Lingua",
    helpCenter: "Centro Assistenza",
    privacy: "Privacy",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Vai in fondo",
    back: "Indietro",
    errorTitle: "Qualcosa è andato storto",
    errorMessage: "Aggiorna la pagina o riprova più tardi.",
    refresh: "Aggiorna pagina",
    syncing: "Sincronizzazione...",
    syncError: "Errore di sincronizzazione",
    pendingChanges: "modifiche in sospeso",
    login: "Accedi",
    signupForFree: "Registrati gratuitamente",
    account: "Account",
    levelA1: "Principiante",
    levelA1Desc: "Frasi di base e presentazioni",
    levelA2: "Elementare",
    levelA2Desc: "Conversazioni quotidiane semplici",
    levelB1: "Intermedio",
    levelB1Desc: "Comunicazione chiara su argomenti familiari",
    levelB2: "Intermedio superiore",
    levelB2Desc: "Argomentazione sicura e discussioni",
    levelC1: "Avanzato",
    levelC1Desc: "Comunicazione fluente e spontanea",
    levelC2: "Competente",
    levelC2Desc: "Padronanza quasi nativa",
  },
  pt: {
    welcomeTitle: "Bem-vindo ao aprendizado de norueguês!",
    selectLevelSubtitle:
      "Selecione seu nível CEFR atual para começar",
    currentLevelSubtitle:
      "Seu nível atual: {level}. Selecione um novo nível para mudar.",
    selectNewLevel: "Selecionar um novo nível",
    selectLanguage: "Selecionar idioma",
    appTitle: "Aprendizado de Norueguês",
    greeting: "Olá!",
    greetingSubtitle: "Como posso ajudá-lo a aprender norueguês hoje?",
    placeholder: "Escreva em norueguês aqui...",
    changeLevel: "Alterar Nível",
    disclaimer:
      "O Aprendizado de Norueguês pode exibir informações imprecisas, então verifique as respostas.",
    progress: "Progresso",
    newChat: "Nova Conversa",
    conversations: "Conversas",
    help: "Ajuda",
    history: "Histórico",
    settings: "Configurações",
    you: "Você",
    tutor: "Tutor",
    theme: "Tema",
    systemMode: "Sistema",
    lightMode: "Claro",
    darkMode: "Escuro",
    language: "Idioma",
    helpCenter: "Central de Ajuda",
    privacy: "Privacidade",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Ir para o final",
    back: "Voltar",
    errorTitle: "Algo deu errado",
    errorMessage: "Por favor, atualize a página ou tente novamente mais tarde.",
    refresh: "Atualizar página",
    syncing: "Sincronizando...",
    syncError: "Erro de sincronização",
    pendingChanges: "alterações pendentes",
    login: "Entrar",
    signupForFree: "Cadastre-se gratuitamente",
    account: "Conta",
    levelA1: "Iniciante",
    levelA1Desc: "Frases básicas e apresentações",
    levelA2: "Elementar",
    levelA2Desc: "Conversas cotidianas simples",
    levelB1: "Intermediário",
    levelB1Desc: "Comunicação clara sobre tópicos familiares",
    levelB2: "Intermediário superior",
    levelB2Desc: "Argumentação confiante e discussões",
    levelC1: "Avançado",
    levelC1Desc: "Comunicação fluente e espontânea",
    levelC2: "Competente",
    levelC2Desc: "Domínio quase nativo",
  },
  nl: {
    welcomeTitle: "Welkom bij Noors leren!",
    selectLevelSubtitle:
      "Selecteer uw huidige CEFR-niveau om te beginnen",
    currentLevelSubtitle:
      "Uw huidige niveau: {level}. Selecteer een nieuw niveau om te wijzigen.",
    selectNewLevel: "Nieuw niveau selecteren",
    selectLanguage: "Taal selecteren",
    appTitle: "Noors Leren",
    greeting: "Hallo!",
    greetingSubtitle: "Hoe kan ik u vandaag helpen met het leren van Noors?",
    placeholder: "Schrijf hier in het Noors...",
    changeLevel: "Niveau Wijzigen",
    disclaimer:
      "Noors Leren kan onnauwkeurige informatie weergeven, controleer de antwoorden.",
    progress: "Voortgang",
    newChat: "Nieuw Gesprek",
    conversations: "Gesprekken",
    help: "Hulp",
    history: "Geschiedenis",
    settings: "Instellingen",
    you: "U",
    tutor: "Tutor",
    theme: "Thema",
    systemMode: "Systeem",
    lightMode: "Licht",
    darkMode: "Donker",
    language: "Taal",
    helpCenter: "Helpcentrum",
    privacy: "Privacy",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Ga naar beneden",
    back: "Terug",
    errorTitle: "Er is iets misgegaan",
    errorMessage: "Ververs de pagina of probeer het later opnieuw.",
    refresh: "Pagina vernieuwen",
    syncing: "Synchroniseren...",
    syncError: "Synchronisatiefout",
    pendingChanges: "wachtende wijzigingen",
    login: "Inloggen",
    signupForFree: "Gratis registreren",
    account: "Account",
    levelA1: "Beginner",
    levelA1Desc: "Basiszinnen en introducties",
    levelA2: "Elementair",
    levelA2Desc: "Eenvoudige alledaagse gesprekken",
    levelB1: "Gemiddeld",
    levelB1Desc: "Duidelijke communicatie over vertrouwde onderwerpen",
    levelB2: "Boven gemiddeld",
    levelB2Desc: "Zelfverzekerde argumentatie en discussies",
    levelC1: "Gevorderd",
    levelC1Desc: "Vloeiende en spontane communicatie",
    levelC2: "Vaardig",
    levelC2Desc: "Bijna moedertaalniveau",
  },
  sv: {
    welcomeTitle: "Välkommen till norsk inlärning!",
    selectLevelSubtitle:
      "Välj din nuvarande CEFR-nivå för att börja",
    currentLevelSubtitle:
      "Din nuvarande nivå: {level}. Välj en ny nivå för att ändra.",
    selectNewLevel: "Välj en ny nivå",
    selectLanguage: "Välj språk",
    appTitle: "Norsk Inlärning",
    greeting: "Hej!",
    greetingSubtitle: "Hur kan jag hjälpa dig att lära dig norska idag?",
    placeholder: "Skriv på norska här...",
    changeLevel: "Ändra Nivå",
    disclaimer:
      "Norsk Inlärning kan visa felaktig information, dubbelkolla svaren.",
    progress: "Framsteg",
    newChat: "Ny Konversation",
    conversations: "Konversationer",
    help: "Hjälp",
    history: "Historik",
    settings: "Inställningar",
    you: "Du",
    tutor: "Handledare",
    theme: "Tema",
    systemMode: "System",
    lightMode: "Ljus",
    darkMode: "Mörk",
    language: "Språk",
    helpCenter: "Hjälpcenter",
    privacy: "Integritet",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Gå till slutet",
    back: "Tillbaka",
    errorTitle: "Något gick fel",
    errorMessage: "Vänligen uppdatera sidan eller försök igen senare.",
    refresh: "Uppdatera sida",
    syncing: "Synkroniserar...",
    syncError: "Synkroniseringsfel",
    pendingChanges: "väntande ändringar",
    login: "Logga in",
    signupForFree: "Registrera dig gratis",
    account: "Konto",
    levelA1: "Nybörjare",
    levelA1Desc: "Grundläggande fraser och introduktioner",
    levelA2: "Elementär",
    levelA2Desc: "Enkla vardagssamtal",
    levelB1: "Medel",
    levelB1Desc: "Tydlig kommunikation om bekanta ämnen",
    levelB2: "Övre medel",
    levelB2Desc: "Självsäker argumentation och diskussioner",
    levelC1: "Avancerad",
    levelC1Desc: "Flytande och spontan kommunikation",
    levelC2: "Skicklig",
    levelC2Desc: "Nästan modersmål",
  },
  da: {
    welcomeTitle: "Velkommen til norsk læring!",
    selectLevelSubtitle:
      "Vælg dit nuværende CEFR-niveau for at begynde",
    currentLevelSubtitle:
      "Dit nuværende niveau: {level}. Vælg et nyt niveau for at ændre.",
    selectNewLevel: "Vælg nyt niveau",
    selectLanguage: "Vælg sprog",
    appTitle: "Norsk Læring",
    greeting: "Hej!",
    greetingSubtitle: "Hvordan kan jeg hjælpe dig med at lære norsk i dag?",
    placeholder: "Skriv på norsk her...",
    changeLevel: "Ændre Niveau",
    disclaimer:
      "Norsk Læring kan vise unøjagtige oplysninger, tjek svarene.",
    progress: "Fremskridt",
    newChat: "Ny Samtale",
    conversations: "Samtaler",
    help: "Hjælp",
    history: "Historik",
    settings: "Indstillinger",
    you: "Dig",
    tutor: "Vejleder",
    theme: "Tema",
    systemMode: "System",
    lightMode: "Lys",
    darkMode: "Mørk",
    language: "Sprog",
    helpCenter: "Hjælpecenter",
    privacy: "Privatliv",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Gå til bund",
    back: "Tilbage",
    errorTitle: "Noget gik galt",
    errorMessage: "Opdater venligst siden eller prøv igen senere.",
    refresh: "Opdater side",
    syncing: "Synkroniserer...",
    syncError: "Synkroniseringsfejl",
    pendingChanges: "ventende ændringer",
    login: "Log ind",
    signupForFree: "Tilmeld dig gratis",
    account: "Konto",
    levelA1: "Begynder",
    levelA1Desc: "Grundlæggende sætninger og introduktioner",
    levelA2: "Elementær",
    levelA2Desc: "Enkle hverdagslige samtaler",
    levelB1: "Mellemniveau",
    levelB1Desc: "Klar kommunikation om velkendte emner",
    levelB2: "Øvre mellemniveau",
    levelB2Desc: "Selvsikker argumentation og diskussioner",
    levelC1: "Avanceret",
    levelC1Desc: "Flydende og spontan kommunikation",
    levelC2: "Dygtig",
    levelC2Desc: "Næsten modersmålsniveau",
  },
  fi: {
    welcomeTitle: "Tervetuloa norjan oppimiseen!",
    selectLevelSubtitle:
      "Valitse nykyinen CEFR-tasosi aloittaaksesi",
    currentLevelSubtitle:
      "Nykyinen tasosi: {level}. Valitse uusi taso vaihtaaksesi.",
    selectNewLevel: "Valitse uusi taso",
    selectLanguage: "Valitse kieli",
    appTitle: "Norjan Oppiminen",
    greeting: "Hei!",
    greetingSubtitle: "Kuinka voin auttaa sinua oppimaan norjaa tänään?",
    placeholder: "Kirjoita norjaksi tähän...",
    changeLevel: "Vaihda Tasoa",
    disclaimer:
      "Norjan Oppiminen voi näyttää epätarkkoja tietoja, tarkista vastaukset.",
    progress: "Edistyminen",
    newChat: "Uusi Keskustelu",
    conversations: "Keskustelut",
    help: "Ohje",
    history: "Historia",
    settings: "Asetukset",
    you: "Sinä",
    tutor: "Ohjaaja",
    theme: "Teema",
    systemMode: "Järjestelmä",
    lightMode: "Vaalea",
    darkMode: "Tumma",
    language: "Kieli",
    helpCenter: "Ohjekeskus",
    privacy: "Yksityisyys",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Siirry alkuun",
    back: "Takaisin",
    errorTitle: "Jotain meni pieleen",
    errorMessage: "Päivitä sivu tai yritä myöhemmin uudelleen.",
    refresh: "Päivitä sivu",
    syncing: "Synkronoidaan...",
    syncError: "Synkronointivirhe",
    pendingChanges: "odottavat muutokset",
    login: "Kirjaudu sisään",
    signupForFree: "Rekisteröidy ilmaiseksi",
    account: "Tili",
    levelA1: "Aloittelija",
    levelA1Desc: "Peruslauseet ja esittelyt",
    levelA2: "Alkeistaso",
    levelA2Desc: "Yksinkertaiset arjen keskustelut",
    levelB1: "Keskitaso",
    levelB1Desc: "Selkeä viestintä tutuista aiheista",
    levelB2: "Ylempi keskitaso",
    levelB2Desc: "Itsevarma argumentointi ja keskustelut",
    levelC1: "Edistynyt",
    levelC1Desc: "Sujuva ja spontaani viestintä",
    levelC2: "Taitava",
    levelC2Desc: "Lähes äidinkielisen tason",
  },
  pl: {
    welcomeTitle: "Witamy w nauce norweskiego!",
    selectLevelSubtitle:
      "Wybierz swój obecny poziom CEFR, aby rozpocząć",
    currentLevelSubtitle:
      "Twój obecny poziom: {level}. Wybierz nowy poziom, aby zmienić.",
    selectNewLevel: "Wybierz nowy poziom",
    selectLanguage: "Wybierz język",
    appTitle: "Nauka Norweskiego",
    greeting: "Cześć!",
    greetingSubtitle: "Jak mogę Ci pomóc w nauce norweskiego dzisiaj?",
    placeholder: "Napisz po norwesku tutaj...",
    changeLevel: "Zmień Poziom",
    disclaimer:
      "Nauka Norweskiego może wyświetlać nieprawidłowe informacje, sprawdź odpowiedzi.",
    progress: "Postęp",
    newChat: "Nowa Rozmowa",
    conversations: "Rozmowy",
    help: "Pomoc",
    history: "Historia",
    settings: "Ustawienia",
    you: "Ty",
    tutor: "Korepetytor",
    theme: "Motyw",
    systemMode: "System",
    lightMode: "Jasny",
    darkMode: "Ciemny",
    language: "Język",
    helpCenter: "Centrum Pomocy",
    privacy: "Prywatność",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Przejdź do końca",
    back: "Wstecz",
    errorTitle: "Coś poszło nie tak",
    errorMessage: "Odśwież stronę lub spróbuj ponownie później.",
    refresh: "Odśwież stronę",
    syncing: "Synchronizowanie...",
    syncError: "Błąd synchronizacji",
    pendingChanges: "oczekujące zmiany",
    login: "Zaloguj się",
    signupForFree: "Zarejestruj się za darmo",
    account: "Konto",
    levelA1: "Początkujący",
    levelA1Desc: "Podstawowe zwroty i przedstawienia",
    levelA2: "Podstawowy",
    levelA2Desc: "Proste codzienne rozmowy",
    levelB1: "Średnio zaawansowany",
    levelB1Desc: "Jasna komunikacja na znane tematy",
    levelB2: "Powyżej średniego",
    levelB2Desc: "Pewna argumentacja i dyskusje",
    levelC1: "Zaawansowany",
    levelC1Desc: "Płynna i spontaniczna komunikacja",
    levelC2: "Biegły",
    levelC2Desc: "Niemal rodzimy poziom",
  },
  uk: {
    welcomeTitle: "Ласкаво просимо до вивчення норвезької!",
    selectLevelSubtitle:
      "Виберіть свій поточний рівень CEFR, щоб розпочати",
    currentLevelSubtitle:
      "Ваш поточний рівень: {level}. Виберіть новий рівень, щоб змінити.",
    selectNewLevel: "Вибрати новий рівень",
    selectLanguage: "Вибрати мову",
    appTitle: "Вивчення Норвезької",
    greeting: "Привіт!",
    greetingSubtitle: "Як я можу допомогти вам вивчати норвезьку сьогодні?",
    placeholder: "Напишіть норвезькою тут...",
    changeLevel: "Змінити Рівень",
    disclaimer:
      "Вивчення Норвезької може відображати неточну інформацію, перевірте відповіді.",
    progress: "Прогрес",
    newChat: "Нова Розмова",
    conversations: "Розмови",
    help: "Допомога",
    history: "Історія",
    settings: "Налаштування",
    you: "Ви",
    tutor: "Репетитор",
    theme: "Тема",
    systemMode: "Система",
    lightMode: "Світла",
    darkMode: "Темна",
    language: "Мова",
    helpCenter: "Центр Допомоги",
    privacy: "Конфіденційність",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Перейти вниз",
    back: "Назад",
    errorTitle: "Щось пішло не так",
    errorMessage: "Будь ласка, оновіть сторінку або спробуйте ще раз пізніше.",
    refresh: "Оновити сторінку",
    syncing: "Синхронізація...",
    syncError: "Помилка синхронізації",
    pendingChanges: "очікуючі зміни",
    login: "Увійти",
    signupForFree: "Зареєструватися безкоштовно",
    account: "Обліковий запис",
    levelA1: "Початковий",
    levelA1Desc: "Базові фрази та привітання",
    levelA2: "Елементарний",
    levelA2Desc: "Прості повсякденні розмови",
    levelB1: "Середній",
    levelB1Desc: "Чітке спілкування на знайомі теми",
    levelB2: "Вище середнього",
    levelB2Desc: "Впевнена аргументація та обговорення",
    levelC1: "Просунутий",
    levelC1Desc: "Вільне та спонтанне спілкування",
    levelC2: "Вільне володіння",
    levelC2Desc: "Майже рівень носія мови",
  },
};

export const isValidLanguageCode = (
  value: string,
): value is LanguageCode => SUPPORTED_LANGUAGES.some((lang) => lang.code === value);

export const getTranslation = (
  language: LanguageCode,
  key: keyof Translations,
  params?: Record<string, string>,
): string => {
  const translation = translations[language][key] ?? translations[DEFAULT_LANGUAGE][key];
  if (!params) return translation;
  return Object.entries(params).reduce(
    (acc, [paramKey, paramValue]) => acc.replace(`{${paramKey}}`, paramValue),
    translation,
  );
};
