export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська" },
] as const;

export type LanguageCode = (typeof SUPPORTED_LANGUAGES)[number]["code"];

export const DEFAULT_LANGUAGE: LanguageCode = "en";

export interface Translations {
  welcomeTitle: string;
  selectLevelSubtitle: string;
  currentLevelSubtitle: string;
  selectNewLevel: string;
  selectLanguage: string;
  appTitle: string;
  greeting: string;
  greetingSubtitle: string;
  placeholder: string;
  changeLevel: string;
  disclaimer: string;
  progress: string;
  newChat: string;
  conversations: string;
  help: string;
  history: string;
  settings: string;
  you: string;
  tutor: string;
  theme: string;
  systemMode: string;
  lightMode: string;
  darkMode: string;
  language: string;
  languageDescription: string;
  helpCenter: string;
  privacy: string;
  levelA1: string;
  levelA1Desc: string;
  levelA2: string;
  levelA2Desc: string;
  levelB1: string;
  levelB1Desc: string;
  levelB2: string;
  levelB2Desc: string;
  suggestionStart: string;
  suggestionV2: string;
  suggestionGrammar: string;
  suggestionTask: string;
  jumpToBottom: string;
  back: string;
  errorTitle: string;
  errorMessage: string;
  refresh: string;
  syncing: string;
  syncError: string;
  pendingChanges: string;
  login: string;
  signupForFree: string;
  authNudgeTitle: string;
  authNudgeBody: string;
  authNudgeSignIn: string;
  authNudgeDismiss: string;
  account: string;
  changeLanguage: string;
  changeLanguageWarning: string;
  confirm: string;
  cancel: string;
  languageSelectionTitle: string;
  languageSelectionSubtitle: string;
  accessibility: string;
  highContrastMode: string;
  accessibilityDescription: string;
  faqDescription: string;
  faqHowItWorks: string;
  faqHowItWorksAnswer: string;
  faqProgress: string;
  faqProgressAnswer: string;
  faqCEFR: string;
  faqCEFRAnswer: string;
  faqChangeLevel: string;
  faqChangeLevelAnswer: string;
  faqLanguage: string;
  faqLanguageAnswer: string;
  faqSaveProgress: string;
  faqSaveProgressAnswer: string;
  // Dashboard page translations
  dashboard: string;
  welcomeBack: string;
  dashboardSubtitle: string;
  progressionBannerLevelUp: string;
  progressionBannerLevelDown: string;
  progressionBannerExercise: string;
  progressionReviewLevels: string;
  progressionDismiss: string;
  writing: string;
  writingDesc: string;
  findTutor: string;
  findTutorDesc: string;
  startChat: string;
  browseTutors: string;
  footerCopyright: string;
  // Tutors page translations
  findNorwegianTutor: string;
  bookLessons: string;
  searchPlaceholder: string;
  availability: string;
  price: string;
  moreFilters: string;
  certifiedTeacher: string;
  communityTutor: string;
  lessons: string;
  rate: string;
  bookTrial: string;
  message: string;
  viewAllTutors: string;
  findTutors: string;
  tryAgain: string;
  newExercise: string;
  exerciseCorrectLabel: string;
  selectExerciseToBegin: string;
  exerciseHowPractice: string;
  exerciseChooseModeSubtitle: string;
  exerciseChooseTopic: string;
  exerciseChooseGrammar: string;
}

const shared: Omit<
  Translations,
  | "welcomeTitle"
  | "selectLevelSubtitle"
  | "currentLevelSubtitle"
  | "selectNewLevel"
  | "selectLanguage"
  | "appTitle"
> = {
  greeting: "Hello!",
  greetingSubtitle: "How can I help you learn Norwegian today?",
  placeholder: "Write in Norwegian here...",
  changeLevel: "Change Level",
  disclaimer:
    "Norwegian Learning may display inaccurate information, so double-check the responses.",
  progress: "Progress",
  newChat: "New Chat",
  conversations: "Conversations",
  help: "Help",
  history: "History",
  settings: "Settings",
  you: "You",
  tutor: "Tutor",
  theme: "Theme",
  systemMode: "System",
  lightMode: "Light",
  darkMode: "Dark",
  language: "Language",
  languageDescription: "Select your preferred interface language.",
  helpCenter: "Help Center",
  privacy: "Privacy",
  levelA1: "A1 Beginner",
  levelA1Desc: "Start your journey here. Learn basic greetings, survival phrases, and simple sentence structures. Perfect for absolute beginners.",
  levelA2: "A2 Elementary",
  levelA2Desc: "Build confidence in everyday situations. Engage in simple conversations about yourself, your family, and your immediate surroundings.",
  levelB1: "B1 Intermediate",
  levelB1Desc: "Gain independence. Understand the main points of clear standard input and deal with most situations likely to arise while travelling.",
  levelB2: "B2 Upper Intermediate",
  levelB2Desc: "Achieve fluency. Understand complex text on concrete and abstract topics, including technical discussions in your field.",
  suggestionStart: "Hei, jeg heter...",
  suggestionV2: "Forklar V2-regelen",
  suggestionGrammar: "Hjelp meg med grammatikk",
  suggestionTask: "Gi meg en oppgave",
  jumpToBottom: "Jump to bottom",
  back: "Back",
  errorTitle: "Something went wrong",
  errorMessage: "Please refresh the page or try again later.",
  refresh: "Refresh Page",
  syncing: "Syncing...",
  syncError: "Sync error",
  pendingChanges: "pending changes",
  login: "Log in",
  signupForFree: "Sign up for free",
  authNudgeTitle: "Save your progress across devices",
  authNudgeBody:
    "Create a free account to sync your conversations. You can keep chatting without signing in.",
  authNudgeSignIn: "Sign in",
  authNudgeDismiss: "Not now",
  account: "Account",
  changeLanguage: "Change Language",
  changeLanguageWarning: "Changing the language will delete all your conversations and reset your progress. This action cannot be undone. Do you want to continue?",
  confirm: "Continue",
  cancel: "Cancel",
  languageSelectionTitle: "Welcome to Norwegian Learning!",
  languageSelectionSubtitle: "Please select your preferred language for the interface",
  accessibility: "Accessibility",
  highContrastMode: "High Contrast Mode",
  accessibilityDescription: "Adjust accessibility settings to improve your experience.",
  faqDescription: "Frequently asked questions about how the app works.",
  faqHowItWorks: "How does the app work?",
  faqHowItWorksAnswer: "The app uses AI to have conversations with you in Norwegian. You select your CEFR level (A1-B2), and the tutor adapts questions and feedback to your level. You practice by responding in Norwegian, and the tutor provides corrections and explanations.",
  faqProgress: "How is my progress calculated?",
  faqProgressAnswer: "Your progress is calculated based on the quality of your responses. The AI evaluates your fluency, vocabulary, grammar, and coherence. Progress can increase or decrease based on your performance, and you'll see your current level on the progress bar.",
  faqCEFR: "What are CEFR levels?",
  faqCEFRAnswer: "CEFR (Common European Framework of Reference) is an international standard for language proficiency. A1 is beginner, A2 is elementary, and B1-B2 are intermediate levels. You can change your level at any time from the level selection page.",
  faqChangeLevel: "How do I change my level?",
  faqChangeLevelAnswer: "Click the 'Change Level' button in the header, or use the back button to return to the level selection page. Select a new level to start a fresh conversation at that level.",
  faqLanguage: "Can I change the interface language?",
  faqLanguageAnswer: "Yes! You can change the interface language in Settings. Note that changing the language will reset all your conversations and progress, as the tutor adapts to your selected language.",
  faqSaveProgress: "How do I save my progress?",
  faqSaveProgressAnswer: "Sign up for a free account to sync your progress across devices. Without an account, your progress is stored locally in your browser.",
  // Dashboard page translations
  dashboard: "Dashboard",
  welcomeBack: "Welcome back, {name}",
  dashboardSubtitle: "Welcome to NorskTutor language learning dashboard.",
  progressionBannerLevelUp:
    "You're progressing — ready to try {level}? You can change level anytime.",
  progressionBannerLevelDown:
    "This level looks challenging — try {level} for more support?",
  progressionBannerExercise:
    "Try a focused exercise from Writing to break through a plateau.",
  progressionReviewLevels: "Review levels",
  progressionDismiss: "Dismiss",
  writing: "Writing",
  writingDesc: "Practice writing and improve your grammar with our interactive tutor.",
  findTutor: "Find a Tutor",
  findTutorDesc: "Connect with native speakers and professional teachers for 1-on-1 lessons.",
  startChat: "Start Chat",
  browseTutors: "Browse Tutors",
  footerCopyright: "Norsk Tutor © 2026. Made with ❤️ for learning.",
  // Tutors page translations
  findNorwegianTutor: "Find a Norwegian Tutor",
  bookLessons: "Book 1-on-1 lessons with native speakers and certified teachers.",
  searchPlaceholder: "Search by name or keyword...",
  availability: "Availability",
  price: "Price",
  moreFilters: "More Filters",
  certifiedTeacher: "Certified Teacher",
  communityTutor: "Community Tutor",
  lessons: "lessons",
  rate: "Rate",
  bookTrial: "Book Trial",
  message: "Message",
  viewAllTutors: "View all 142 tutors",
  findTutors: "Find Tutors",
  tryAgain: "Try again",
  newExercise: "New Exercise",
  exerciseCorrectLabel: "correct",
  selectExerciseToBegin: "Select an exercise mode above to begin...",
  exerciseHowPractice: "How would you like to practice?",
  exerciseChooseModeSubtitle: "Choose an exercise mode to get started",
  exerciseChooseTopic: "Choose a topic",
  exerciseChooseGrammar: "Choose a grammar focus",
};

const translations: Record<LanguageCode, Translations> = {
  en: {
    welcomeTitle: "Welcome to Norwegian Learning!",
    selectLevelSubtitle: "Select your current CEFR level to begin",
    currentLevelSubtitle:
      "Your current level: {level}. Select a new level to change.",
    selectNewLevel: "Select a new level to change",
    selectLanguage: "Select Language",
    ...shared,
    appTitle: "Norwegian Learning",
  },
  no: {
    welcomeTitle: "Velkommen til Norsk Læring!",
    selectLevelSubtitle: "Velg ditt nåværende CEFR-nivå for å begynne",
    currentLevelSubtitle:
      "Ditt nåværende nivå: {level}. Velg et nytt nivå for å endre.",
    selectNewLevel: "Velg et nytt nivå for å endre",
    selectLanguage: "Velg språk",
    languageSelectionTitle: "Velkommen til Norsk Læring!",
    languageSelectionSubtitle: "Vennligst velg ditt foretrukne språk for grensesnittet",
    appTitle: "Norsk Læring",
    greeting: "Hei!",
    greetingSubtitle: "Hvordan kan jeg hjelpe deg med å lære norsk i dag?",
    placeholder: "Skriv på norsk her...",
    changeLevel: "Endre Nivå",
    disclaimer:
      "Norsk Læring kan vise unøyaktig informasjon, så dobbeltsjekk svarene.",
    progress: "Framgang",
    newChat: "Ny Samtale",
    conversations: "Samtaler",
    help: "Hjelp",
    history: "Historikk",
    settings: "Innstillinger",
    you: "Deg",
    tutor: "Veileder",
    theme: "Tema",
    systemMode: "System",
    lightMode: "Lys",
    darkMode: "Mørk",
    language: "Språk",
    languageDescription: "Velg ditt foretrukne grensesnittspråk.",
    helpCenter: "Hjelpesenter",
    privacy: "Personvern",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg med grammatikk",
    suggestionTask: "Gi meg en oppgave",
    jumpToBottom: "Gå til bunn",
    back: "Tilbake",
    errorTitle: "Noe gikk galt",
    errorMessage: "Vennligst oppdater siden eller prøv igjen senere.",
    refresh: "Oppdater side",
    syncing: "Synkroniserer...",
    syncError: "Synkroniseringsfeil",
    pendingChanges: "ventende endringer",
    login: "Logg inn",
    signupForFree: "Registrer deg gratis",
    authNudgeTitle: "Lagre fremgangen på tvers av enheter",
    authNudgeBody:
      "Opprett en gratis konto for å synkronisere samtalene dine. Du kan fortsette å chatte uten å logge inn.",
    authNudgeSignIn: "Logg inn",
    authNudgeDismiss: "Ikke nå",
    account: "Konto",
    changeLanguage: "Endre språk",
    changeLanguageWarning: "Å endre språket vil slette alle samtaler og tilbakestille fremgangen din. Denne handlingen kan ikke angres. Vil du fortsette?",
    confirm: "Fortsett",
    cancel: "Avbryt",
    levelA1: "Nybegynner",
    levelA1Desc: "Grunnleggende fraser og introduksjoner",
    levelA2: "Elementær",
    levelA2Desc: "Enkle hverdagslige samtaler",
    levelB1: "Mellomnivå",
    levelB1Desc: "Klare kommunikasjon om kjente emner",
    levelB2: "Øvre mellomnivå",
    levelB2Desc: "Selvsikker argumentasjon og diskusjoner",
    accessibility: "Tilgjengelighet",
    highContrastMode: "Høy kontrast modus",
    accessibilityDescription: "Juster tilgjengelighetsinnstillinger for å forbedre opplevelsen din.",
    faqDescription: "Ofte stilte spørsmål om hvordan appen fungerer.",
    faqHowItWorks: "Hvordan fungerer appen?",
    faqHowItWorksAnswer: "Appen bruker AI til å ha samtaler med deg på norsk. Du velger ditt CEFR-nivå (A1-B2), og veilederen tilpasser spørsmål og tilbakemeldinger til ditt nivå. Du øver ved å svare på norsk, og veilederen gir korreksjoner og forklaringer.",
    faqProgress: "Hvordan beregnes fremgangen min?",
    faqProgressAnswer: "Fremgangen din beregnes basert på kvaliteten på svarene dine. AI-en evaluerer flyt, ordforråd, grammatikk og sammenheng. Fremgang kan øke eller reduseres basert på ytelsen din, og du vil se ditt nåværende nivå på fremgangslinjen.",
    faqCEFR: "Hva er CEFR-nivåer?",
    faqCEFRAnswer: "CEFR (Common European Framework of Reference) is en internasjonal standard for språkferdigheter. A1 er nybegynner, A2 er elementært, og B1-B2 er mellomnivå. Du kan endre nivået ditt når som helst fra nivåvalgsiden.",
    faqChangeLevel: "Hvordan endrer jeg nivået mitt?",
    faqChangeLevelAnswer: "Klikk på 'Endre Nivå'-knappen i toppteksten, eller bruk tilbake-knappen for å gå tilbake til nivåvalgsiden. Velg et nytt nivå for å starte en ny samtale på det nivået.",
    faqLanguage: "Kan jeg endre grensesnittspråket?",
    faqLanguageAnswer: "Ja! Du kan endre grensesnittspråket i Innstillinger. Merk at endring av språket vil tilbakestille alle samtaler og fremgang, da veilederen tilpasser seg ditt valgte språk.",
    faqSaveProgress: "Hvordan lagrer jeg fremgangen min?",
    faqSaveProgressAnswer: "Registrer deg for en gratis konto for å synkronisere fremgangen din på tvers av enheter. Uten en konto lagres fremgangen din lokalt i nettleseren din.",
    // Dashboard page translations
    dashboard: "Oversikt",
    welcomeBack: "Velkommen tilbake, {name}",
    dashboardSubtitle: "Velkommen til NorskTutor språklæringsoversikt.",
    progressionBannerLevelUp:
      "Du gjør fremgang — klar for {level}? Du kan endre nivå når som helst.",
    progressionBannerLevelDown:
      "Dette nivået ser utfordrende ut — prøv {level} for mer støtte?",
    progressionBannerExercise:
      "Prøv en målrettet øvelse under Skriving for å komme videre.",
    progressionReviewLevels: "Se nivåer",
    progressionDismiss: "Lukk",
        writing: "Skriving",
    writingDesc: "Øv på skriving og forbedre grammatikken din med vår interaktive veileder.",
    findTutor: "Finn en veileder",
    findTutorDesc: "Koble deg til morsmålsbrukere og profesjonelle lærere for 1-til-1 leksjoner.",
      startChat: "Start chat",
    browseTutors: "Se veiledere",
      footerCopyright: "Norsk Tutor © 2026. Laget med ❤️ for læring.",
    // Tutors page translations
    findNorwegianTutor: "Finn en norsk veileder",
    bookLessons: "Bestill 1-til-1 leksjoner med morsmålsbrukere og sertifiserte lærere.",
    searchPlaceholder: "Søk på navn eller nøkkelord...",
    availability: "Tilgjengelighet",
    price: "Pris",
    moreFilters: "Flere filtre",
    certifiedTeacher: "Sertifisert lærer",
    communityTutor: "Samfunnsveileder",
    lessons: "leksjoner",
    rate: "Pris",
    bookTrial: "Bestill prøvetime",
    message: "Melding",
    viewAllTutors: "Se alle 142 veiledere",
    findTutors: "Finn veiledere",
    tryAgain: "Prøv igjen",
    newExercise: "Ny øvelse",
    exerciseCorrectLabel: "riktig",
    selectExerciseToBegin: "Velg en øvelsesmodus over for å begynne...",
    exerciseHowPractice: "Hvordan vil du øve?",
    exerciseChooseModeSubtitle: "Velg en øvelsesmodus for å komme i gang",
    exerciseChooseTopic: "Velg et tema",
    exerciseChooseGrammar: "Velg grammatikkfokus",
    },
  de: {
    welcomeTitle: "Willkommen beim Norwegischlernen!",
    selectLevelSubtitle: "Wählen Sie Ihr aktuelles GER-Niveau, um zu beginnen",
    currentLevelSubtitle:
      "Ihr aktuelles Niveau: {level}. Wählen Sie ein neues Niveau zum Ändern.",
    selectNewLevel: "Neues Niveau auswählen",
    selectLanguage: "Sprache auswählen",
    languageSelectionTitle: "Willkommen beim Norwegischlernen!",
    languageSelectionSubtitle: "Bitte wählen Sie Ihre bevorzugte Sprache für die Benutzeroberfläche",
    appTitle: "Norwegisch lernen",
    greeting: "Hallo!",
    greetingSubtitle: "Wie kann ich Ihnen heute beim Norwegischlernen helfen?",
    placeholder: "Schreiben Sie hier auf Norwegisch...",
    changeLevel: "Niveau ändern",
    disclaimer:
      "Norwegisch lernen kann ungenaue Informationen anzeigen, bitte überprüfen Sie die Antworten.",
    progress: "Fortschritt",
    newChat: "Neuer Chat",
    conversations: "Unterhaltungen",
    help: "Hilfe",
    history: "Verlauf",
    settings: "Einstellungen",
    you: "Sie",
    tutor: "Tutor",
    theme: "Design",
    systemMode: "System",
    lightMode: "Hell",
    darkMode: "Dunkel",
    language: "Sprache",
    languageDescription: "Wählen Sie Ihre bevorzugte Benutzeroberflächensprache.",
    helpCenter: "Hilfezentrum",
    privacy: "Datenschutz",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-regelen",
    suggestionGrammar: "Hjelp meg mit Grammatik",
    suggestionTask: "Geben Sie mir eine Aufgabe",
    jumpToBottom: "Zum Ende springen",
    back: "Zurück",
    errorTitle: "Etwas ist schief gelaufen",
    errorMessage: "Bitte aktualisieren Sie die Seite oder versuchen Sie es später erneut.",
    refresh: "Seite aktualisieren",
    syncing: "Synchronisierung...",
    syncError: "Synchronisierungsfehler",
    pendingChanges: "ausstehende Änderungen",
    login: "Anmelden",
    signupForFree: "Kostenlos registrieren",
    authNudgeTitle: "Save your progress across devices",
    authNudgeBody:
      "Create a free account to sync your conversations. You can keep chatting without signing in.",
    authNudgeSignIn: "Sign in",
    authNudgeDismiss: "Not now",
    account: "Konto",
    changeLanguage: "Sprache ändern",
    changeLanguageWarning: "Das Ändern der Sprache löscht alle Ihre Unterhaltungen und setzt Ihren Fortschritt zurück. Diese Aktion kann nicht rückgängig gemacht werden. Möchten Sie fortfahren?",
    confirm: "Fortfahren",
    cancel: "Abbrechen",
    levelA1: "Anfänger",
    levelA1Desc: "Grundlegende Phrasen und Einführungen",
    levelA2: "Elementar",
    levelA2Desc: "Einfache alltägliche Gespräche",
    levelB1: "Mittelstufe",
    levelB1Desc: "Klare Kommunikation über vertraute Themen",
    levelB2: "Obere Mittelstufe",
    levelB2Desc: "Selbstbewusste Argumentation und Diskussionen",
    accessibility: "Barrierefreiheit",
    highContrastMode: "Hoher Kontrast Modus",
    accessibilityDescription: "Passen Sie die Barrierefreiheitseinstellungen an, um Ihre Erfahrung zu verbessern.",
    faqDescription: "Häufig gestellte Fragen zur Funktionsweise der App.",
    faqHowItWorks: "Wie funktioniert die App?",
    faqHowItWorksAnswer: "Die App nutzt KI, um Gespräche mit Ihnen auf Norwegisch zu führen. Sie wählen Ihr GER-Niveau (A1-B2), und der Tutor passt Fragen und Feedback an Ihr Niveau an. Sie üben, indem Sie auf Norwegisch antworten, und der Tutor bietet Korrekturen und Erklärungen.",
    faqProgress: "Wie wird mein Fortschritt berechnet?",
    faqProgressAnswer: "Ihr Fortschritt wird basierend auf der Qualität Ihrer Antworten berechnet. Die KI bewertet Ihre Sprachgewandtheit, Ihren Wortschatz, Ihre Grammatik und Ihre Kohärenz. Der Fortschritt kann je nach Ihrer Leistung steigen oder sinken, und Sie sehen Ihr aktuelles Niveau in der Fortschrittsleiste.",
    faqCEFR: "Was sind GER-Niveaus?",
    faqCEFRAnswer: "GER (Gemeinsamer Europäischer Referenzrahmen) ist ein internationaler Standard für Sprachkenntnisse. A1 ist Anfänger, A2 ist elementar, und B1-B2 sind Mittelstufe. Sie können Ihr Niveau jederzeit von der Niveauauswahlseite ändern.",
    faqChangeLevel: "Wie ändere ich mein Niveau?",
    faqChangeLevelAnswer: "Klicken Sie auf die Schaltfläche 'Niveau ändern' in der Kopfzeile oder verwenden Sie die Zurück-Schaltfläche, um zur Niveauauswahlseite zurückzukehren. Wählen Sie ein neues Niveau, um ein neues Gespräch auf diesem Niveau zu beginnen.",
    faqLanguage: "Kann ich die Benutzeroberflächensprache ändern?",
    faqLanguageAnswer: "Ja! Sie können die Benutzeroberflächensprache in den Einstellungen ändern. Beachten Sie, dass das Ändern der Sprache alle Ihre Gespräche zurücksetzt und Ihren Fortschritt zurücksetzt, da sich der Tutor an Ihre ausgewählte Sprache anpasst.",
    faqSaveProgress: "Wie speichere ich meinen Fortschritt?",
    faqSaveProgressAnswer: "Registrieren Sie sich für ein kostenloses Konto, um Ihren Fortschritt geräteübergreifend zu synchronisieren. Ohne Konto wird Ihr Fortschritt lokal in Ihrem Browser gespeichert.",
    // Dashboard page translations
    dashboard: "Übersicht",
    welcomeBack: "Willkommen zurück, {name}",
    dashboardSubtitle: "Willkommen beim NorskTutor Sprachlern-Dashboard.",
    progressionBannerLevelUp:
      "You're progressing — ready to try {level}? You can change level anytime.",
    progressionBannerLevelDown:
      "This level looks challenging — try {level} for more support?",
    progressionBannerExercise:
      "Try a focused exercise from Writing to break through a plateau.",
    progressionReviewLevels: "Review levels",
    progressionDismiss: "Dismiss",
        writing: "Schreiben",
    writingDesc: "Üben Sie das Schreiben und verbessern Sie Ihre Grammatik mit unserem interaktiven Tutor.",
    findTutor: "Tutor finden",
    findTutorDesc: "Vernetzen Sie sich mit Muttersprachlern und professionellen Lehrern für Einzelunterricht.",
      startChat: "Chat starten",
    browseTutors: "Tutoren durchsuchen",
      footerCopyright: "Norsk Tutor © 2026. Mit ❤️ zum Lernen gemacht.",
    // Tutors page translations
    findNorwegianTutor: "Norwegisch-Tutor finden",
    bookLessons: "Buchen Sie Einzelunterricht bei Muttersprachlern und zertifizierten Lehrern.",
    searchPlaceholder: "Nach Name oder Stichwort suchen...",
    availability: "Verfügbarkeit",
    price: "Preis",
    moreFilters: "Weitere Filter",
    certifiedTeacher: "Zertifizierter Lehrer",
    communityTutor: "Community-Tutor",
    lessons: "Lektionen",
    rate: "Preis",
    bookTrial: "Probestunde buchen",
    message: "Nachricht",
    viewAllTutors: "Alle 142 Tutoren anzeigen",
    findTutors: "Tutoren finden",
    tryAgain: "Erneut versuchen",
    newExercise: "Neue Übung",
    exerciseCorrectLabel: "richtig",
    selectExerciseToBegin: "Wählen Sie oben einen Übungsmodus, um zu beginnen...",
    exerciseHowPractice: "Wie möchten Sie üben?",
    exerciseChooseModeSubtitle: "Wählen Sie einen Übungsmodus, um zu beginnen",
    exerciseChooseTopic: "Wählen Sie ein Thema",
    exerciseChooseGrammar: "Wählen Sie einen Grammatikschwerpunkt",
    },
  fr: {
    welcomeTitle: "Bienvenue à l'apprentissage du norvégien !",
    selectLevelSubtitle:
      "Sélectionnez votre niveau CECR actuel pour commencer",
    currentLevelSubtitle:
      "Votre niveau actuel : {level}. Sélectionnez un nouveau niveau pour changer.",
    selectNewLevel: "Sélectionner un nouveau niveau",
    selectLanguage: "Sélectionner la langue",
    languageSelectionTitle: "Bienvenue à l'apprentissage du norvégien !",
    languageSelectionSubtitle: "Veuillez sélectionner votre langue préférée pour l'interface",
    appTitle: "Apprentissage du Norvégien",
    greeting: "Bonjour !",
    greetingSubtitle: "Comment puis-je vous aider à apprendre le norvégien aujourd'hui ?",
    placeholder: "Écrivez en norvégien ici...",
    changeLevel: "Changer de Niveau",
    disclaimer:
      "L'Apprentissage du Norvégien peut afficher des informations inexactes, veuillez vérifier les réponses.",
    progress: "Progrès",
    newChat: "Nouvelle Conversation",
    conversations: "Conversations",
    help: "Aide",
    history: "Historique",
    settings: "Paramètres",
    you: "Vous",
    tutor: "Tuteur",
    theme: "Thème",
    systemMode: "Système",
    lightMode: "Clair",
    darkMode: "Sombre",
    language: "Langue",
    languageDescription: "Sélectionnez votre langue d'interface préférée.",
    helpCenter: "Centre d'Aide",
    privacy: "Confidentialité",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Expliquez la règle V2",
    suggestionGrammar: "Aidez-moi avec la grammaire",
    suggestionTask: "Donnez-moi une tâche",
    jumpToBottom: "Aller en bas",
    back: "Retour",
    errorTitle: "Une erreur s'est produite",
    errorMessage: "Veuillez actualiser la page ou réessayer plus tard.",
    refresh: "Actualiser la page",
    syncing: "Synchronisation...",
    syncError: "Erreur de synchronisation",
    pendingChanges: "modifications en attente",
    login: "Se connecter",
    signupForFree: "S'inscrire gratuitement",
    authNudgeTitle: "Save your progress across devices",
    authNudgeBody:
      "Create a free account to sync your conversations. You can keep chatting without signing in.",
    authNudgeSignIn: "Sign in",
    authNudgeDismiss: "Not now",
    account: "Compte",
    changeLanguage: "Changer de langue",
    changeLanguageWarning: "Changer la langue supprimera toutes vos conversations et réinitialisera votre progression. Cette action ne peut pas être annulée. Voulez-vous continuer?",
    confirm: "Continuer",
    cancel: "Annuler",
    levelA1: "Débutant",
    levelA1Desc: "Phrases de base et présentations",
    levelA2: "Élémentaire",
    levelA2Desc: "Conversations quotidiennes simples",
    levelB1: "Intermédiaire",
    levelB1Desc: "Communication claire sur des sujets familiers",
    levelB2: "Intermédiaire supérieur",
    levelB2Desc: "Argumentation confiante et discussions",
    accessibility: "Accessibilité",
    highContrastMode: "Mode Contraste Élevé",
    accessibilityDescription: "Ajustez les paramètres d'accessibilité pour améliorer votre expérience.",
    faqDescription: "Questions fréquemment posées sur le fonctionnement de l'application.",
    faqHowItWorks: "Comment fonctionne l'application?",
    faqHowItWorksAnswer: "L'application utilise l'IA pour avoir des conversations avec vous en norvégien. Vous sélectionnez votre niveau CECR (A1-B2), et le tuteur adapte les questions et les commentaires à votre niveau. Vous pratiquez en répondant en norvégien, et le tuteur fournit des corrections et des explications.",
    faqProgress: "Comment mon progrès est-il calculé?",
    faqProgressAnswer: "Votre progrès est calculé en fonction de la qualité de vos réponses. L'IA évalue votre fluidité, votre vocabulaire, votre grammaire et votre cohérence. Le progrès peut augmenter ou diminuer en fonction de votre performance, et vous verrez votre niveau actuel sur la barre de progression.",
    faqCEFR: "Qu'est-ce que les niveaux CECR?",
    faqCEFRAnswer: "CECR (Cadre Européen Commun de Référence) est une norme internationale pour les compétences linguistiques. A1 est débutant, A2 est élémentaire, et B1-B2 sont des niveaux intermédiaires. Vous pouvez changer votre niveau à tout moment depuis la page de sélection de niveau.",
    faqChangeLevel: "Comment puis-je changer mon niveau?",
    faqChangeLevelAnswer: "Cliquez sur le bouton 'Changer de Niveau' dans l'en-tête, ou utilisez le bouton retour pour revenir à la page de sélection de niveau. Sélectionnez un nouveau niveau pour commencer une nouvelle conversation à ce niveau.",
    faqLanguage: "Puis-je changer la langue de l'interface?",
    faqLanguageAnswer: "Oui! Vous pouvez changer la langue de l'interface dans les Paramètres. Notez que changer la langue réinitialisera toutes vos conversations et votre progression, car le tuteur s'adapte à votre langue sélectionnée.",
    faqSaveProgress: "Comment puis-je sauvegarder mon progrès?",
    faqSaveProgressAnswer: "Inscrivez-vous pour un compte gratuit pour synchroniser votre progrès sur tous les appareils. Sans compte, votre progrès est stocké localement dans votre navigateur.",
    // Dashboard page translations
    dashboard: "Tableau de bord",
    welcomeBack: "Bon retour, {name}",
    dashboardSubtitle: "Bienvenue sur le tableau de bord d'apprentissage de NorskTutor.",
    progressionBannerLevelUp:
      "You're progressing — ready to try {level}? You can change level anytime.",
    progressionBannerLevelDown:
      "This level looks challenging — try {level} for more support?",
    progressionBannerExercise:
      "Try a focused exercise from Writing to break through a plateau.",
    progressionReviewLevels: "Review levels",
    progressionDismiss: "Dismiss",
        writing: "Écrire",
    writingDesc: "Pratiquez l'écriture et améliorez votre grammaire avec notre tuteur interactif.",
    findTutor: "Trouver un tuteur",
    findTutorDesc: "Connectez-vous avec des locuteurs natifs et des professeurs professionnels pour des cours particuliers.",
      startChat: "Commencer le chat",
    browseTutors: "Parcourir les tuteurs",
      footerCopyright: "Norsk Tutor © 2026. Fait avec ❤️ pour l'apprentissage.",
    // Tutors page translations
    findNorwegianTutor: "Trouver un tuteur de norvégien",
    bookLessons: "Réservez des cours particuliers avec des locuteurs natifs et des professeurs certifiés.",
    searchPlaceholder: "Rechercher par nom ou par mot-clé...",
    availability: "Disponibilité",
    price: "Prix",
    moreFilters: "Plus de filtres",
    certifiedTeacher: "Professeur certifié",
    communityTutor: "Tuteur de la communauté",
    lessons: "leçons",
    rate: "Tarif",
    bookTrial: "Réserver un essai",
    message: "Message",
    viewAllTutors: "Voir les 142 tuteurs",
    findTutors: "Trouver des tuteurs",
    tryAgain: "Réessayer",
    newExercise: "Nouvel exercice",
    exerciseCorrectLabel: "correct",
    selectExerciseToBegin: "Sélectionnez un mode d'exercice ci-dessus pour commencer...",
    exerciseHowPractice: "Comment souhaitez-vous pratiquer ?",
    exerciseChooseModeSubtitle: "Choisissez un mode d'exercice pour commencer",
    exerciseChooseTopic: "Choisissez un sujet",
    exerciseChooseGrammar: "Choisissez un objectif grammatical",
    },
  es: {
    welcomeTitle: "¡Bienvenido al aprendizaje de noruego!",
    selectLevelSubtitle:
      "Seleccione su nivel actual del MCER para comenzar",
    currentLevelSubtitle:
      "Su nivel actual: {level}. Seleccione un nuevo nivel para cambiar.",
    selectNewLevel: "Seleccionar un nuevo nivel",
    selectLanguage: "Seleccionar idioma",
    languageSelectionTitle: "¡Bienvenido al aprendizaje de noruego!",
    languageSelectionSubtitle: "Seleccione su idioma preferido para la interfaz",
    appTitle: "Aprendizaje de Noruego",
    greeting: "¡Hola!",
    greetingSubtitle: "¿Cómo puedo ayudarte a aprender noruego hoy?",
    placeholder: "Escribe en noruego aquí...",
    changeLevel: "Cambiar Nivel",
    disclaimer:
      "El Aprendizaje de Noruego puede mostrar información inexacta, verifica las respuestas.",
    progress: "Progreso",
    newChat: "Nueva Conversación",
    conversations: "Conversaciones",
    help: "Ayuda",
    history: "Historial",
    settings: "Configuración",
    you: "Tú",
    tutor: "Tutor",
    theme: "Tema",
    systemMode: "Sistema",
    lightMode: "Claro",
    darkMode: "Oscuro",
    language: "Idioma",
    languageDescription: "Selecciona tu idioma de interfaz preferido.",
    helpCenter: "Centro de Ayuda",
    privacy: "Privacidad",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Explica la regla V2",
    suggestionGrammar: "Ayúdame con la gramática",
    suggestionTask: "Dame una tarea",
    jumpToBottom: "Ir al final",
    back: "Volver",
    errorTitle: "Algo salió mal",
    errorMessage: "Por favor, actualice la página o intente nuevamente más tarde.",
    refresh: "Actualizar página",
    syncing: "Sincronizando...",
    syncError: "Error de sincronización",
    pendingChanges: "cambios pendientes",
    login: "Iniciar sesión",
    signupForFree: "Regístrate gratis",
    authNudgeTitle: "Save your progress across devices",
    authNudgeBody:
      "Create a free account to sync your conversations. You can keep chatting without signing in.",
    authNudgeSignIn: "Sign in",
    authNudgeDismiss: "Not now",
    account: "Cuenta",
    changeLanguage: "Cambiar idioma",
    changeLanguageWarning: "Cambiar el idioma eliminará todas tus conversaciones y restablecerá tu progreso. Esta acción no se puede deshacer. ¿Deseas continuar?",
    confirm: "Continuar",
    cancel: "Cancelar",
    levelA1: "Principiante",
    levelA1Desc: "Frases básicas y presentaciones",
    levelA2: "Elemental",
    levelA2Desc: "Conversaciones cotidianas simples",
    levelB1: "Intermedio",
    levelB1Desc: "Comunicación clara sobre temas familiares",
    levelB2: "Intermedio superior",
    levelB2Desc: "Argumentación segura y debates",
    accessibility: "Accesibilidad",
    highContrastMode: "Modo de Alto Contraste",
    accessibilityDescription: "Ajusta la configuración de accesibilidad para mejorar tu experiencia.",
    faqDescription: "Preguntas frecuentes sobre cómo funciona la aplicación.",
    faqHowItWorks: "¿Cómo funciona la aplicación?",
    faqHowItWorksAnswer: "La aplicación usa IA para tener conversaciones contigo en noruego. Seleccionas tu nivel MCER (A1-B2), y el tutor adapta las preguntas y comentarios a tu nivel. Practicas respondiendo en noruego, y el tutor proporciona correcciones y explicaciones.",
    faqProgress: "¿Cómo se calcula mi progreso?",
    faqProgressAnswer: "Tu progreso se calcula según la calidad de tus respuestas. La AI evalúa tu fluidez, vocabulario, gramática y coherencia. El progreso puede aumentar o disminuir según tu rendimiento, y verás tu nivel actual en la barra de progreso.",
    faqCEFR: "¿Qué son los niveles MCER?",
    faqCEFRAnswer: "MCER (Marco Común Europeo de Referencia) es un estándar internacional para las competencias lingüísticas. A1 es principiante, A2 es elemental, y B1-B2 son niveles intermedios. Puedes cambiar tu nivel en cualquier momento desde la página de selección de nivel.",
    faqChangeLevel: "¿Cómo cambio mi nivel?",
    faqChangeLevelAnswer: "Haz clic en el botón 'Cambiar Nivel' en el encabezado, o usa el botón atrás para volver a la página de selección de nivel. Selecciona un nuevo nivel para comenzar una nueva conversación en ese nivel.",
    faqLanguage: "¿Puedo cambiar el idioma de la interfaz?",
    faqLanguageAnswer: "¡Sí! Puedes cambiar el idioma de la interfaz en Configuración. Ten en cuenta que cambiar el idioma restablecerá todas tus conversaciones y tu progreso, ya que el tutor se adapta a tu idioma seleccionado.",
    faqSaveProgress: "¿Cómo guardo mi progreso?",
    faqSaveProgressAnswer: "Regístrate para una cuenta gratuita para sincronizar tu progreso en todos los dispositivos. Sin una cuenta, tu progreso se almacena localmente en tu navegador.",
    // Dashboard page translations
    dashboard: "Panel",
    welcomeBack: "Bienvenido de nuevo, {name}",
    dashboardSubtitle: "Bienvenido al panel de aprendizaje de idiomas de NorskTutor.",
    progressionBannerLevelUp:
      "You're progressing — ready to try {level}? You can change level anytime.",
    progressionBannerLevelDown:
      "This level looks challenging — try {level} for more support?",
    progressionBannerExercise:
      "Try a focused exercise from Writing to break through a plateau.",
    progressionReviewLevels: "Review levels",
    progressionDismiss: "Dismiss",
        writing: "Escribir",
    writingDesc: "Practica la escritura y mejora tu gramática con nuestro tutor interactivo.",
    findTutor: "Encontrar un tutor",
    findTutorDesc: "Conéctate con hablantes nativos y profesores profesionales para lecciones 1 a 1.",
      startChat: "Iniciar chat",
    browseTutors: "Explorar tutores",
      footerCopyright: "Norsk Tutor © 2026. Hecho con ❤️ para aprender.",
    // Tutors page translations
    findNorwegianTutor: "Encontrar un tutor de noruego",
    bookLessons: "Reserva lecciones 1 a 1 con hablantes nativos y profesores certificados.",
    searchPlaceholder: "Buscar por nombre o palabra clave...",
    availability: "Disponibilidad",
    price: "Precio",
    moreFilters: "Más filtros",
    certifiedTeacher: "Profesor certificado",
    communityTutor: "Tutor de la comunidad",
    lessons: "lecciones",
    rate: "Tarifa",
    bookTrial: "Reservar prueba",
    message: "Mensaje",
    viewAllTutors: "Ver los 142 tutores",
    findTutors: "Encontrar tutores",
    tryAgain: "Intentar de nuevo",
    newExercise: "Nuevo ejercicio",
    exerciseCorrectLabel: "correcto",
    selectExerciseToBegin: "Selecciona un modo de ejercicio arriba para empezar...",
    exerciseHowPractice: "¿Cómo te gustaría practicar?",
    exerciseChooseModeSubtitle: "Elige un modo de ejercicio para empezar",
    exerciseChooseTopic: "Elige un tema",
    exerciseChooseGrammar: "Elige un enfoque gramatical",
    },
  it: {
    welcomeTitle: "Benvenuti all'apprendimento del norvegese!",
    selectLevelSubtitle: "Seleziona il tuo livello QCER attuale per iniziare",
    currentLevelSubtitle: "Il tuo livello attuale: {level}. Seleziona un nuovo livello per cambiare.",
    selectNewLevel: "Seleziona un nuovo livello",
    selectLanguage: "Seleziona lingua",
    languageSelectionTitle: "Welcome to Norwegian Learning!",
    languageSelectionSubtitle: "Please select your preferred language",
    appTitle: "Apprendimento del Norvegese",
    greeting: "Ciao!",
    greetingSubtitle: "Come posso aiutarti a imparare il norvegese oggi?",
    placeholder: "Scrivi qui in norvegese...",
    changeLevel: "Cambia Livello",
    disclaimer: "L'apprendimento del norvegese potrebbe mostrare informazioni imprecise, si prega di verificare le risposte.",
    progress: "Progresso",
    newChat: "Nuova Conversazione",
    conversations: "Conversazioni",
    help: "Aiuto",
    history: "Cronologia",
    settings: "Impostazioni",
    you: "Tu",
    tutor: "Tutor",
    theme: "Tema",
    systemMode: "Sistema",
    lightMode: "Chiaro",
    darkMode: "Scuro",
    language: "Lingua",
    languageDescription: "Seleziona la tua lingua di interfaccia preferita.",
    helpCenter: "Centro Assistenza",
    privacy: "Privacy",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Spiega la regola V2",
    suggestionGrammar: "Aiutami con la grammatica",
    suggestionTask: "Dammi un compito",
    jumpToBottom: "Vai in fondo",
    back: "Indietro",
    errorTitle: "Qualcosa è andato storto",
    errorMessage: "Aggiorna la pagina o riprova più tardi.",
    refresh: "Aggiorna pagina",
    syncing: "Sincronizzazione...",
    syncError: "Errore di sincronizzazione",
    pendingChanges: "modifiche in sospeso",
    login: "Accedi",
    signupForFree: "Iscriviti gratuitamente",
    authNudgeTitle: "Save your progress across devices",
    authNudgeBody:
      "Create a free account to sync your conversations. You can keep chatting without signing in.",
    authNudgeSignIn: "Sign in",
    authNudgeDismiss: "Not now",
    account: "Account",
    changeLanguage: "Cambia lingua",
    changeLanguageWarning: "Cambiare la lingua eliminerà tutte le tue conversazioni e ripristinerà i tuoi progressi. Questa azione non può essere annullata. Vuoi continuare?",
    confirm: "Continua",
    cancel: "Annulla",
    levelA1: "Principiante",
    levelA1Desc: "Frasi di base e presentazioni",
    levelA2: "Elementare",
    levelA2Desc: "Semplici conversazioni quotidiane",
    levelB1: "Intermedio",
    levelB1Desc: "Comunicazione chiara su argomenti familiari",
    levelB2: "Intermedio superiore",
    levelB2Desc: "Argomentazione e discussioni sicure",
    accessibility: "Accessibilità",
    highContrastMode: "Modalità Contrasto Elevato",
    accessibilityDescription: "Regola le impostazioni di accessibilità per migliorare la tua esperienza.",
    faqDescription: "Domande frequenti su come funziona l'app.",
    faqHowItWorks: "Come funziona l'app?",
    faqHowItWorksAnswer: "L'app utilizza l'IA per avere conversazioni con te in norvegese. Selezioni il tuo livello QCER (A1-B2) e il tutor adatta domande e feedback al tuo livello. Ti eserciti rispondendo in norvegese e il tutor fornisce correzioni e spiegazioni.",
    faqProgress: "Come viene calcolato il mio progresso?",
    faqProgressAnswer: "Il tuo progresso viene calcolato in base alla qualità delle tue risposte. L'IA valuta la tua fluidità, il vocabolario, la grammatica e la coerenza. Il progresso può aumentare o diminuire a seconda delle tue prestazioni e vedrai il tuo livello attuale nella barra di avanzamento.",
    faqCEFR: "Cosa sono i livelli QCER?",
    faqCEFRAnswer: "QCER (Quadro Comune Europeo di Riferimento) è uno standard internazionale per le competenze linguistiche. A1 è principiante, A2 è elementare, e B1-B2 sono livelli intermedi. Puoi cambiare il tuo livello in qualsiasi momento dalla pagina di selezione del livello.",
    faqChangeLevel: "Come posso cambiare il mio livello?",
    faqChangeLevelAnswer: "Fai clic sul pulsante 'Cambia Livello' nell'intestazione o usa il pulsante Indietro per tornare alla pagina di selezione del livello. Seleziona un nuovo livello per iniziare una nuova conversazione a quel livello.",
    faqLanguage: "Posso cambiare la lingua dell'interfaccia?",
    faqLanguageAnswer: "Sì! Puoi cambiare la lingua dell'interfaccia nelle Impostazioni. Tieni presente che cambiare la lingua ripristinerà tutte le tue conversazioni e i tuoi progressi, poiché il tutor si adatta alla lingua selezionata.",
    faqSaveProgress: "Come posso salvare i miei progressi?",
    faqSaveProgressAnswer: "Registrati per un account gratuito per sincronizzare i tuoi progressi su tutti i dispositivi. Senza un account, i tuoi progressi vengono archiviati localmente nel tuo browser.",
    // Dashboard page translations
    dashboard: "Dashboard",
    welcomeBack: "Bentornato, {name}",
    dashboardSubtitle: "Benvenuto nella dashboard di apprendimento delle lingue di NorskTutor.",
    progressionBannerLevelUp:
      "You're progressing — ready to try {level}? You can change level anytime.",
    progressionBannerLevelDown:
      "This level looks challenging — try {level} for more support?",
    progressionBannerExercise:
      "Try a focused exercise from Writing to break through a plateau.",
    progressionReviewLevels: "Review levels",
    progressionDismiss: "Dismiss",
        writing: "Scrivere",
    writingDesc: "Esercitati a scrivere e migliora la tua grammatica con il nostro tutor interattivo.",
    findTutor: "Trova un tutor",
    findTutorDesc: "Connettiti con madrelingua e insegnanti professionisti per lezioni individuali.",
      startChat: "Inizia chat",
    browseTutors: "Sfoglia tutor",
      footerCopyright: "Norsk Tutor © 2026. Realizzato con ❤️ per l'apprendimento.",
    // Tutors page translations
    findNorwegianTutor: "Trova un tutor di norvegese",
    bookLessons: "Prenota lezioni individuali con madrelingua e insegnanti certificati.",
    searchPlaceholder: "Cerca per nome o parola chiave...",
    availability: "Disponibilità",
    price: "Prezzo",
    moreFilters: "Altri filtri",
    certifiedTeacher: "Insegnante certificato",
    communityTutor: "Tutor della comunità",
    lessons: "lezioni",
    rate: "Tariffa",
    bookTrial: "Prenota una lezione di prova",
    message: "Messaggio",
    viewAllTutors: "Visualizza tutti i 142 tutor",
    findTutors: "Trova tutor",
    tryAgain: "Riprova",
    newExercise: "Nuovo esercizio",
    exerciseCorrectLabel: "corretti",
    selectExerciseToBegin: "Seleziona una modalità di esercizio sopra per iniziare...",
    exerciseHowPractice: "Come vuoi esercitarti?",
    exerciseChooseModeSubtitle: "Scegli una modalità di esercizio per iniziare",
    exerciseChooseTopic: "Scegli un argomento",
    exerciseChooseGrammar: "Scegli un focus grammaticale",
    },
  pt: {
    welcomeTitle: "Bem-vindo ao aprendizado de norueguês!",
    selectLevelSubtitle: "Selecione seu nível CEFR atual para começar",
    currentLevelSubtitle:
      "Seu nível atual: {level}. Selecione um novo nível para mudar.",
    selectNewLevel: "Selecionar um novo nível",
    selectLanguage: "Selecionar idioma",
    languageSelectionTitle: "Welcome to Norwegian Learning!",
    languageSelectionSubtitle: "Please select your preferred language",
    appTitle: "Aprendizado de Norueguês",
    greeting: "Olá!",
    greetingSubtitle: "Como posso ajudar você a aprender norueguês hoje?",
    placeholder: "Escreva em norueguês aqui...",
    changeLevel: "Mudar Nível",
    disclaimer: "O Aprendizado de Norueguês pode exibir informações imprecisas, por favor, verifique as respostas.",
    progress: "Progresso",
    newChat: "Nova Conversa",
    conversations: "Conversas",
    help: "Ajuda",
    history: "Histórico",
    settings: "Configurações",
    you: "Você",
    tutor: "Tutor",
    theme: "Tema",
    systemMode: "Sistema",
    lightMode: "Claro",
    darkMode: "Escuro",
    language: "Idioma",
    languageDescription: "Selecione seu idioma de interface preferido.",
    helpCenter: "Central de Ajuda",
    privacy: "Privacidade",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Explique a regra V2",
    suggestionGrammar: "Ajude-me com a gramática",
    suggestionTask: "Dê-me uma tarefa",
    jumpToBottom: "Ir para o final",
    back: "Voltar",
    errorTitle: "Algo deu errado",
    errorMessage: "Por favor, atualize a página ou tente novamente mais tarde.",
    refresh: "Atualizar página",
    syncing: "Sincronizando...",
    syncError: "Erro de sincronização",
    pendingChanges: "alterações pendentes",
    login: "Entrar",
    signupForFree: "Cadastre-se gratuitamente",
    authNudgeTitle: "Save your progress across devices",
    authNudgeBody:
      "Create a free account to sync your conversations. You can keep chatting without signing in.",
    authNudgeSignIn: "Sign in",
    authNudgeDismiss: "Not now",
    account: "Conta",
    changeLanguage: "Mudar idioma",
    changeLanguageWarning: "Mudar o idioma apagará todas as suas conversas e redefinirá seu progresso. Esta ação não pode ser desfeita. Deseja continuar?",
    confirm: "Continuar",
    cancel: "Cancelar",
    levelA1: "Iniciante",
    levelA1Desc: "Frases básicas e apresentações",
    levelA2: "Elementar",
    levelA2Desc: "Conversas diárias simples",
    levelB1: "Intermediário",
    levelB1Desc: "Comunicação clara sobre tópicos familiares",
    levelB2: "Intermediário Superior",
    levelB2Desc: "Argumentação e discussões confiantes",
    accessibility: "Acessibilidade",
    highContrastMode: "Modo de Alto Contraste",
    accessibilityDescription: "Ajuste as configurações de acessibilidade para melhorar sua experiência.",
    faqDescription: "Perguntas frequentes sobre como o aplicativo funciona.",
    faqHowItWorks: "Como o aplicativo funciona?",
    faqHowItWorksAnswer: "O aplicativo usa IA para ter conversas com você em norueguês. Você seleciona seu nível CEFR (A1-B2), e o tutor adapta as perguntas e o feedback ao seu nível. Você pratica respondendo em norueguês, e o tutor fornece correções e explicações.",
    faqProgress: "Como meu progresso é calculado?",
    faqProgressAnswer: "Seu progresso é calculado com base na qualidade de suas respostas. A IA avalia sua fluência, vocabulário, gramática e coerência. O progresso pode aumentar ou diminuir dependendo do seu desempenho, e você verá seu nível atual na barra de progresso.",
    faqCEFR: "O que são os níveis CEFR?",
    faqCEFRAnswer: "CEFR (Common European Framework of Reference) é um padrão internacional para proficiência em idiomas. A1 é iniciante, A2 é elementar, e B1-B2 são níveis intermediários. Você pode mudar seu nível a qualquer momento na página de seleção de nível.",
    faqChangeLevel: "Como mudo meu nível?",
    faqChangeLevelAnswer: "Clique no botão 'Mudar Nível' no cabeçalho, ou use o botão voltar para retornar à página de seleção de nível. Selecione um novo nível para iniciar uma nova conversa nesse nível.",
    faqLanguage: "Posso mudar o idioma da interface?",
    faqLanguageAnswer: "Sim! Você pode mudar o idioma da interface nas Configurações. Observe que mudar o idioma redefinirá todas as suas conversas e seu progresso, pois o tutor se adapta ao idioma selecionado.",
    faqSaveProgress: "Como salvo meu progresso?",
    faqSaveProgressAnswer: "Cadastre-se para uma conta gratuita para sincronizar seu progresso em todos os dispositivos. Sem uma conta, seu progresso é armazenado localmente em seu navegador.",
    // Dashboard page translations
    dashboard: "Painel",
    welcomeBack: "Bem-vindo de volta, {name}",
    dashboardSubtitle: "Bem-vindo ao painel de aprendizado de idiomas NorskTutor.",
    progressionBannerLevelUp:
      "You're progressing — ready to try {level}? You can change level anytime.",
    progressionBannerLevelDown:
      "This level looks challenging — try {level} for more support?",
    progressionBannerExercise:
      "Try a focused exercise from Writing to break through a plateau.",
    progressionReviewLevels: "Review levels",
    progressionDismiss: "Dismiss",
        writing: "Escrever",
    writingDesc: "Pratique a escrita e melhore sua gramática com nosso tutor interativo.",
    findTutor: "Encontrar um tutor",
    findTutorDesc: "Conecte-se com falantes nativos e professores profissionais para aulas individuais.",
      startChat: "Iniciar chat",
    browseTutors: "Procurar tutores",
      footerCopyright: "Norsk Tutor © 2026. Feito com ❤️ para aprender.",
    // Tutors page translations
    findNorwegianTutor: "Encontrar um tutor de norueguês",
    bookLessons: "Reserve aulas individuais com falantes nativos e professores certificados.",
    searchPlaceholder: "Pesquisar por nome ou palavra-chave...",
    availability: "Disponibilidade",
    price: "Preço",
    moreFilters: "Mais filtros",
    certifiedTeacher: "Professor certificado",
    communityTutor: "Tutor da comunidade",
    lessons: "aulas",
    rate: "Taxa",
    bookTrial: "Reservar aula experimental",
    message: "Mensagem",
    viewAllTutors: "Ver todos os 142 tutores",
    findTutors: "Encontrar tutores",
    tryAgain: "Tentar novamente",
    newExercise: "Novo exercício",
    exerciseCorrectLabel: "corretos",
    selectExerciseToBegin: "Selecione um modo de exercício acima para começar...",
    exerciseHowPractice: "Como você quer praticar?",
    exerciseChooseModeSubtitle: "Escolha um modo de exercício para começar",
    exerciseChooseTopic: "Escolha um tópico",
    exerciseChooseGrammar: "Escolha um foco gramatical",
    },
  nl: {
    welcomeTitle: "Welkom bij Noors leren!",
    selectLevelSubtitle: "Selecteer uw huidige CEFR-niveau om te beginnen",
    currentLevelSubtitle:
      "Uw huidige niveau: {level}. Selecteer een nieuw niveau om te wijzigen.",
    selectNewLevel: "Nieuw niveau selecteren",
    selectLanguage: "Taal selecteren",
    languageSelectionTitle: "Welcome to Norwegian Learning!",
    languageSelectionSubtitle: "Please select your preferred language",
    appTitle: "Noors Leren",
    greeting: "Hallo!",
    greetingSubtitle: "Hoe kan ik u vandaag helpen met Noors leren?",
    placeholder: "Schrijf hier in het Noors...",
    changeLevel: "Niveau Wijzigen",
    disclaimer: "Noors Leren kan onnauwkeurige informatie weergeven, controleer de antwoorden.",
    progress: "Voortgang",
    newChat: "Nieuw Gesprek",
    conversations: "Gesprekken",
    help: "Hulp",
    history: "Geschiedenis",
    settings: "Instellingen",
    you: "U",
    tutor: "Tutor",
    theme: "Thema",
    systemMode: "Systeem",
    lightMode: "Licht",
    darkMode: "Donker",
    language: "Taal",
    languageDescription: "Selecteer uw voorkeurstaal voor de interface.",
    helpCenter: "Helpcentrum",
    privacy: "Privacy",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Leg de V2-regel uit",
    suggestionGrammar: "Help me met grammatica",
    suggestionTask: "Geef me een taak",
    jumpToBottom: "Naar beneden springen",
    back: "Terug",
    errorTitle: "Er is iets misgegaan",
    errorMessage: "Vernieuw de pagina of probeer het later opnieuw.",
    refresh: "Pagina vernieuwen",
    syncing: "Synchroniseren...",
    syncError: "Synchronisatiefout",
    pendingChanges: "wachtende wijzigingen",
    login: "Inloggen",
    signupForFree: "Gratis aanmelden",
    authNudgeTitle: "Save your progress across devices",
    authNudgeBody:
      "Create a free account to sync your conversations. You can keep chatting without signing in.",
    authNudgeSignIn: "Sign in",
    authNudgeDismiss: "Not now",
    account: "Account",
    changeLanguage: "Taal wijzigen",
    changeLanguageWarning: "Het wijzigen van de taal verwijdert al uw gesprekken en reset uw voortgang. Deze actie kan niet ongedaan worden gemaakt. Wilt u doorgaan?",
    confirm: "Doorgaan",
    cancel: "Annuleren",
    levelA1: "Beginner",
    levelA1Desc: "Basisfrases en introducties",
    levelA2: "Elementair",
    levelA2Desc: "Eenvoudige dagelijkse gesprekken",
    levelB1: "Gemiddeld",
    levelB1Desc: "Duidelijke communicatie over bekende onderwerpen",
    levelB2: "Boven Gemiddeld",
    levelB2Desc: "Zelfverzekerde argumentatie en discussies",
    accessibility: "Toegankelijkheid",
    highContrastMode: "Hoog Contrast Modus",
    accessibilityDescription: "Pas de toegankelijkheidsinstellingen aan om uw ervaring te verbeteren.",
    faqDescription: "Veelgestelde vragen over hoe de app werkt.",
    faqHowItWorks: "Hoe werkt de app?",
    faqHowItWorksAnswer: "De app gebruikt AI om gesprekken met u te voeren in het Noors. U selecteert uw CEFR-niveau (A1-B2), en de tutor past vragen en feedback aan uw niveau aan. U oefent door in het Noors te antwoorden, en de tutor geeft correcties en uitleg.",
    faqProgress: "Hoe wordt mijn voortgang berekend?",
    faqProgressAnswer: "Uw voortgang wordt berekend op basis van de kwaliteit van uw antwoorden. De AI beoordeelt uw spreekvaardigheid, woordenschat, grammatica en coherentie. De voortgang kan stijgen of dalen afhankelijk van uw prestaties, en u ziet uw huidige niveau in de voortgangsbalk.",
    faqCEFR: "Wat zijn CEFR-niveaus?",
    faqCEFRAnswer: "CEFR (Common European Framework of Reference) is een internationale standaard voor taalvaardigheid. A1 is beginner, A2 is elementair, en B1-B2 zijn gemiddelde niveaus. U kunt uw niveau op elk moment wijzigen via de niveaukeuzepagina.",
    faqChangeLevel: "Hoe wijzig ik mijn niveau?",
    faqChangeLevelAnswer: "Klik op de knop 'Niveau Wijzigen' in de header, of gebruik de terugknop om terug te keren naar de niveaukeuzepagina. Selecteer een nieuw niveau om een nieuw gesprek op dat niveau te beginnen.",
    faqLanguage: "Kan ik de interfacetaal wijzigen?",
    faqLanguageAnswer: "Ja! U kunt de interfacetaal wijzigen in de Instellingen. Houd er rekening mee dat het wijzigen van de taal al uw gesprekken en uw voortgang reset, omdat de tutor zich aanpast aan de door u geselecteerde taal.",
    faqSaveProgress: "Hoe sla ik mijn voortgang op?",
    faqSaveProgressAnswer: "Meld u aan voor een gratis account om uw voortgang op alle apparaten te synchroniseren. Zonder account wordt uw voortgang lokaal in uw browser opgeslagen.",
    // Dashboard page translations
    dashboard: "Dashboard",
    welcomeBack: "Welkom terug, {name}",
    dashboardSubtitle: "Welkom bij het NorskTutor taal leer-dashboard.",
    progressionBannerLevelUp:
      "You're progressing — ready to try {level}? You can change level anytime.",
    progressionBannerLevelDown:
      "This level looks challenging — try {level} for more support?",
    progressionBannerExercise:
      "Try a focused exercise from Writing to break through a plateau.",
    progressionReviewLevels: "Review levels",
    progressionDismiss: "Dismiss",
        writing: "Schrijven",
    writingDesc: "Oefen schrijven en verbeter uw grammatica met onze interactieve tutor.",
    findTutor: "Vind een tutor",
    findTutorDesc: "Maak contact met moedertaalsprekers en professionele docenten voor 1-op-1 lessen.",
      startChat: "Chat starten",
    browseTutors: "Tutors zoeken",
      footerCopyright: "Norsk Tutor © 2026. Gemaakt met ❤️ om te leren.",
    // Tutors page translations
    findNorwegianTutor: "Vind een Noorse tutor",
    bookLessons: "Boek 1-op-1 lessen met moedertaalsprekers en gecertificeerde docenten.",
    searchPlaceholder: "Zoeken op naam of trefwoord...",
    availability: "Beschikbaarheid",
    price: "Prijs",
    moreFilters: "Meer filters",
    certifiedTeacher: "Gecertificeerde docent",
    communityTutor: "Community tutor",
    lessons: "lessen",
    rate: "Tarief",
    bookTrial: "Proefles boeken",
    message: "Bericht",
    viewAllTutors: "Bekijk alle 142 tutors",
    findTutors: "Tutors vinden",
    tryAgain: "Opnieuw proberen",
    newExercise: "Nieuwe oefening",
    exerciseCorrectLabel: "goed",
    selectExerciseToBegin: "Selecteer hierboven een oefenmodus om te beginnen...",
    exerciseHowPractice: "Hoe wil je oefenen?",
    exerciseChooseModeSubtitle: "Kies een oefenmodus om te beginnen",
    exerciseChooseTopic: "Kies een onderwerp",
    exerciseChooseGrammar: "Kies een grammaticale focus",
    },
  sv: {
    welcomeTitle: "Välkommen till norsk inlärning!",
    selectLevelSubtitle: "Välj din nuvarande CEFR-nivå för att börja",
    currentLevelSubtitle:
      "Din nuvarande nivå: {level}. Välj en ny nivå för att ändra.",
    selectNewLevel: "Välj en ny nivå",
    selectLanguage: "Välj språk",
    languageSelectionTitle: "Welcome to Norwegian Learning!",
    languageSelectionSubtitle: "Please select your preferred language",
    appTitle: "Norsk Inlärning",
    greeting: "Hej!",
    greetingSubtitle: "Hur kan jag hjälpa dig att lära dig norska idag?",
    placeholder: "Skriv på norska här...",
    changeLevel: "Ändra Nivå",
    disclaimer: "Norsk Inlärning kan visa felaktig information, vänligen verifiera svaren.",
    progress: "Framsteg",
    newChat: "Ny Konversation",
    conversations: "Konversationer",
    help: "Hjälp",
    history: "Historik",
    settings: "Inställningar",
    you: "Du",
    tutor: "Tutor",
    theme: "Tema",
    systemMode: "System",
    lightMode: "Ljus",
    darkMode: "Mörk",
    language: "Språk",
    languageDescription: "Välj ditt föredragna gränssnittsspråk.",
    helpCenter: "Hjälpcenter",
    privacy: "Integritet",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Förklara V2-regeln",
    suggestionGrammar: "Hjälp mig med grammatik",
    suggestionTask: "Ge mig en uppgift",
    jumpToBottom: "Gå till botten",
    back: "Tillbaka",
    errorTitle: "Något gick fel",
    errorMessage: "Vänligen uppdatera sidan eller försök igen senare.",
    refresh: "Uppdatera sida",
    syncing: "Synkroniserar...",
    syncError: "Synkroniseringsfel",
    pendingChanges: "väntande ändringar",
    login: "Logga in",
    signupForFree: "Registrera dig gratis",
    authNudgeTitle: "Save your progress across devices",
    authNudgeBody:
      "Create a free account to sync your conversations. You can keep chatting without signing in.",
    authNudgeSignIn: "Sign in",
    authNudgeDismiss: "Not now",
    account: "Konto",
    changeLanguage: "Ändra språk",
    changeLanguageWarning: "Att ändra språk kommer att radera alla dina konversationer och återställa dina framsteg. Denna åtgärd kan inte ångras. Vill du fortsätta?",
    confirm: "Fortsätt",
    cancel: "Avbryt",
    levelA1: "Nybörjare",
    levelA1Desc: "Grundläggande fraser och introduktioner",
    levelA2: "Elementär",
    levelA2Desc: "Enkla vardagliga konversationer",
    levelB1: "Medel",
    levelB1Desc: "Tydlig kommunikation om bekanta ämnen",
    levelB2: "Övre Medel",
    levelB2Desc: "Självsäker argumentation och diskussioner",
    accessibility: "Tillgänglighet",
    highContrastMode: "Högkontrastläge",
    accessibilityDescription: "Justera tillgänglighetsinställningarna för att förbättra din upplevelse.",
    faqDescription: "Vanliga frågor om hur appen fungerar.",
    faqHowItWorks: "Hur fungerar appen?",
    faqHowItWorksAnswer: "Appen använder AI för att ha konversationer med dig på norska. Du väljer din CEFR-nivå (A1-B2), och handledaren anpassar frågor och feedback till din nivå. Du övar genom att svara på norska, och handledaren ger korrigeringar och förklaringar.",
    faqProgress: "Hur beräknas mina framsteg?",
    faqProgressAnswer: "Dina framsteg beräknas baserat på kvaliteten på dina svar. AI bedömer din flyt, ordförråd, grammatikk och koherens. Framstegen kan öka eller minska beroende på din prestation, och du ser din nuvarande nivå i framstegsfältet.",
    faqCEFR: "Vad är CEFR-nivåer?",
    faqCEFRAnswer: "CEFR (Common European Framework of Reference) är en internationell standard för språkfärdigheter. A1 är nybörjare, A2 är elementär, och B1-B2 är medelnivåer. Du kan ändra din nivå när som helst från nivåvalsidan.",
    faqChangeLevel: "Hur ändrar jag min nivå?",
    faqChangeLevelAnswer: "Klicka på knappen 'Ändra Nivå' i sidhuvudet, eller använd bakåtknappen för att återgå till nivåvalsidan. Välj en ny nivå för att starta en ny konversation på den nivån.",
    faqLanguage: "Kan jag ändra gränssnittsspråket?",
    faqLanguageAnswer: "Ja! Du kan ändra gränssnittsspråket i Inställningar. Observera att om du ändrar språk återställs alla dina konversationer och dina framsteg, eftersom handledaren anpassar sig till ditt valda språk.",
    faqSaveProgress: "Hur sparar jag mina framsteg?",
    faqSaveProgressAnswer: "Registrera dig för ett gratis konto för att synkronisera dina framsteg över enheter. Utan ett konto lagras dina framsteg lokalt i din webbläsare.",
    // Dashboard page translations
    dashboard: "Instrumentpanel",
    welcomeBack: "Välkommen tillbaka, {name}",
    dashboardSubtitle: "Välkommen till NorskTutors språkinlärningspanel.",
    progressionBannerLevelUp:
      "You're progressing — ready to try {level}? You can change level anytime.",
    progressionBannerLevelDown:
      "This level looks challenging — try {level} for more support?",
    progressionBannerExercise:
      "Try a focused exercise from Writing to break through a plateau.",
    progressionReviewLevels: "Review levels",
    progressionDismiss: "Dismiss",
        writing: "Skriva",
    writingDesc: "Öva på att skriva och förbättra din grammatik med vår interaktiva handledare.",
    findTutor: "Hitta en handledare",
    findTutorDesc: "Få kontakt med modersmålstalare och professionella lärare för 1-till-1-lektioner.",
      startChat: "Starta chatt",
    browseTutors: "Bläddra bland handledare",
      footerCopyright: "Norsk Tutor © 2026. Gjord med ❤️ för lärande.",
    // Tutors page translations
    findNorwegianTutor: "Hitta en norsk handledare",
    bookLessons: "Boka 1-till-1-lektioner med modersmålstalare och certifierade lärare.",
    searchPlaceholder: "Sök efter namn eller nyckelord...",
    availability: "Tillgänglighet",
    price: "Pris",
    moreFilters: "Fler filter",
    certifiedTeacher: "Certifierad lärare",
    communityTutor: "Community-handledare",
    lessons: "lektioner",
    rate: "Pris",
    bookTrial: "Boka provlektion",
    message: "Meddelande",
    viewAllTutors: "Visa alla 142 handledare",
    findTutors: "Hitta handledare",
    tryAgain: "Försök igen",
    newExercise: "Ny övning",
    exerciseCorrectLabel: "rätt",
    selectExerciseToBegin: "Välj ett övningsläge ovan för att börja...",
    exerciseHowPractice: "Hur vill du öva?",
    exerciseChooseModeSubtitle: "Välj ett övningsläge för att komma igång",
    exerciseChooseTopic: "Välj ett ämne",
    exerciseChooseGrammar: "Välj grammatikfokus",
    },
  da: {
    welcomeTitle: "Velkommen til norsk læring!",
    selectLevelSubtitle: "Vælg dit nuværende CEFR-niveau for at begynde",
    currentLevelSubtitle:
      "Dit nuværende niveau: {level}. Vælg et nyt niveau for at ændre.",
    selectNewLevel: "Vælg nyt niveau",
    selectLanguage: "Vælg sprog",
    languageSelectionTitle: "Welcome to Norwegian Learning!",
    languageSelectionSubtitle: "Please select your preferred language",
    appTitle: "Norsk Læring",
    greeting: "Hej!",
    greetingSubtitle: "Hvordan kan jeg hjælpe dig med at lære norsk i dag?",
    placeholder: "Skriv på norsk her...",
    changeLevel: "Skift Niveau",
    disclaimer: "Norsk Læring kan vise unøjagtige oplysninger, venligst verificer svarene.",
    progress: "Fremskridt",
    newChat: "Ny Samtale",
    conversations: "Samtaler",
    help: "Hjælp",
    history: "Historik",
    settings: "Indstillinger",
    you: "Du",
    tutor: "Tutor",
    theme: "Tema",
    systemMode: "System",
    lightMode: "Lys",
    darkMode: "Mørk",
    language: "Sprog",
    languageDescription: "Vælg dit foretrukne sprog til brugerfladen.",
    helpCenter: "Hjælpecenter",
    privacy: "Privatliv",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Forklar V2-reglen",
    suggestionGrammar: "Hjælp mig med grammatik",
    suggestionTask: "Giv mig en opgave",
    jumpToBottom: "Gå til bunden",
    back: "Tilbage",
    errorTitle: "Noget gik galt",
    errorMessage: "Venligst opdater siden eller prøv igen senere.",
    refresh: "Opdater side",
    syncing: "Synkroniserer...",
    syncError: "Synkroniseringsfejl",
    pendingChanges: "afventende ændringer",
    login: "Log ind",
    signupForFree: "Tilmeld dig gratis",
    authNudgeTitle: "Save your progress across devices",
    authNudgeBody:
      "Create a free account to sync your conversations. You can keep chatting without signing in.",
    authNudgeSignIn: "Sign in",
    authNudgeDismiss: "Not now",
    account: "Konto",
    changeLanguage: "Skift sprog",
    changeLanguageWarning: "At skifte sprog vil slette alle dine samtaler og nulstille din fremgang. Denne handling kan ikke fortrydes. Vil du fortsætte?",
    confirm: "Fortsæt",
    cancel: "Annuller",
    levelA1: "Begynder",
    levelA1Desc: "Grundlæggende sætninger og introduktioner",
    levelA2: "Elementær",
    levelA2Desc: "Enkle hverdagssamtaler",
    levelB1: "Mellemliggende",
    levelB1Desc: "Klar kommunikation om kendte emner",
    levelB2: "Øvre Mellemliggende",
    levelB2Desc: "Selvsikker argumentation og diskussioner",
    accessibility: "Tilgængelighed",
    highContrastMode: "Høj Kontrast Tilstand",
    accessibilityDescription: "Juster tilgængelighedsindstillinger for at forbedre din oplevelse.",
    faqDescription: "Ofte stillede spørgsmål om, hvordan appen fungerer.",
    faqHowItWorks: "Hvordan fungerer appen?",
    faqHowItWorksAnswer: "Appen bruger AI til at føre samtaler med dig på norsk. Du vælger dit CEFR-niveau (A1-B2), og tutoren tilpasser spørgsmål og feedback til dit niveau. Du øver dig ved at svare på norsk, og tutoren giver rettelser og forklaringer.",
    faqProgress: "Hvordan beregnes min fremgang?",
    faqProgressAnswer: "Din fremgang beregnes ud fra kvaliteten af dine svar. AI'en vurderer din flydende tale, ordforråd, grammatik og sammenhæng. Fremgangen kan stige eller falde afhængigt af din præstation, og du vil se dit nuværende niveau i fremdriftslinjen.",
    faqCEFR: "Hvad er CEFR-niveauer?",
    faqCEFRAnswer: "CEFR (Common European Framework of Reference) er en internationell standard för sprogfærdigheder. A1 er begynder, A2 er elementær, og B1-B2 er mellemniveauer. Du kan ændre dit niveau når som helst fra niveauvalgssiden.",
    faqChangeLevel: "Hvordan ændrer jeg mit niveau?",
    faqChangeLevelAnswer: "Klik på knappen 'Skift Niveau' i headeren, eller brug tilbage-knappen for at vende tilbage til niveauvalgssiden. Vælg et nyt niveau for at starte en ny samtale på det niveau.",
    faqLanguage: "Kan jeg ændre sproget for brugerfladen?",
    faqLanguageAnswer: "Ja! Du kan ændre sproget for brugerfladen i Indstillinger. Bemærk, at ændring af sprog vil nulstille alle dine samtaler og din fremgang, da tutoren tilpasser sig dit valgte sprog.",
    faqSaveProgress: "Hvordan gemmer jeg min fremgang?",
    faqSaveProgressAnswer: "Tilmeld dig en gratis konto for at synkronisere din fremgang på tværs af enheder. Uden en konto gemmes din fremgang lokalt i din browser.",
    // Dashboard page translations
    dashboard: "Dashboard",
    welcomeBack: "Velkommen tilbage, {name}",
    dashboardSubtitle: "Velkommen til NorskTutor sprogindlærings-dashboard.",
    progressionBannerLevelUp:
      "You're progressing — ready to try {level}? You can change level anytime.",
    progressionBannerLevelDown:
      "This level looks challenging — try {level} for more support?",
    progressionBannerExercise:
      "Try a focused exercise from Writing to break through a plateau.",
    progressionReviewLevels: "Review levels",
    progressionDismiss: "Dismiss",
        writing: "Skrivning",
    writingDesc: "Øv dig i at skrive og forbedre din grammatik med vores interaktive tutor.",
    findTutor: "Find en tutor",
    findTutorDesc: "Få forbindelse med modersmålstalende og professionelle lærere til 1-til-1-undervisning.",
      startChat: "Start chat",
    browseTutors: "Gennemse tutorer",
      footerCopyright: "Norsk Tutor © 2026. Lavet med ❤️ til læring.",
    // Tutors page translations
    findNorwegianTutor: "Find en norsk tutor",
    bookLessons: "Book 1-til-1-undervisning med modersmålstalende og certificerede lærere.",
    searchPlaceholder: "Søg efter navn eller nøgleord...",
    availability: "Tilgængelighed",
    price: "Pris",
    moreFilters: "Flere filtre",
    certifiedTeacher: "Certificeret lærer",
    communityTutor: "Fællesskabstutor",
    lessons: "lektioner",
    rate: "Pris",
    bookTrial: "Book prøvetime",
    message: "Besked",
    viewAllTutors: "Se alle 142 tutorer",
    findTutors: "Find tutorer",
    tryAgain: "Prøv igen",
    newExercise: "Ny øvelse",
    exerciseCorrectLabel: "korrekt",
    selectExerciseToBegin: "Vælg en øvelsestilstand ovenfor for at begynde...",
    exerciseHowPractice: "Hvordan vil du øve?",
    exerciseChooseModeSubtitle: "Vælg en øvelsestilstand for at komme i gang",
    exerciseChooseTopic: "Vælg et emne",
    exerciseChooseGrammar: "Vælg grammatikfokus",
    },
  fi: {
    welcomeTitle: "Tervetuloa norjan oppimiseen!",
    selectLevelSubtitle: "Valitse nykyinen CEFR-tasosi aloittaaksesi",
    currentLevelSubtitle:
      "Nykyinen tasosi: {level}. Valitse uusi taso vaihtaaksesi.",
    selectNewLevel: "Valitse uusi taso",
    selectLanguage: "Valitse kieli",
    languageSelectionTitle: "Welcome to Norwegian Learning!",
    languageSelectionSubtitle: "Please select your preferred language",
    appTitle: "Norjan Oppiminen",
    greeting: "Hei!",
    greetingSubtitle: "Miten voin auttaa sinua oppimaan norjaa tänään?",
    placeholder: "Kirjoita norjaksi tähän...",
    changeLevel: "Vaihda Tasoa",
    disclaimer: "Norjan oppiminen voi näyttää epätarkkoja tietoja, tarkista vastaukset.",
    progress: "Edistyminen",
    newChat: "Uusi Keskustelu",
    conversations: "Keskustelut",
    help: "Apua",
    history: "Historia",
    settings: "Asetukset",
    you: "Sinä",
    tutor: "Tutor",
    theme: "Teema",
    systemMode: "Järjestelmä",
    lightMode: "Vaalea",
    darkMode: "Tumma",
    language: "Kieli",
    languageDescription: "Valitse haluamasi käyttöliittymäkieli.",
    helpCenter: "Ohjekeskus",
    privacy: "Tietosuoja",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Selitä V2-sääntö",
    suggestionGrammar: "Auta minua kieliopissa",
    suggestionTask: "Anna minulle tehtävä",
    jumpToBottom: "Siirry alas",
    back: "Takaisin",
    errorTitle: "Jotain meni pieleen",
    errorMessage: "Päivitä sivu tai yritä myöhemmin uudelleen.",
    refresh: "Päivitä sivu",
    syncing: "Synkronoidaan...",
    syncError: "Synkronointivirhe",
    pendingChanges: "odottavat muutokset",
    login: "Kirjaudu sisään",
    signupForFree: "Rekisteröidy ilmaiseksi",
    authNudgeTitle: "Save your progress across devices",
    authNudgeBody:
      "Create a free account to sync your conversations. You can keep chatting without signing in.",
    authNudgeSignIn: "Sign in",
    authNudgeDismiss: "Not now",
    account: "Tili",
    changeLanguage: "Vaihda kieltä",
    changeLanguageWarning: "Kielen vaihtaminen poistaa kaikki keskustelusi ja nollaa edistymisesi. Tätä toimintoa ei voi kumota. Haluatko jatkaa?",
    confirm: "Jatka",
    cancel: "Peruuta",
    levelA1: "Aloittelija",
    levelA1Desc: "Perusfraasit ja esittelyt",
    levelA2: "Alkeet",
    levelA2Desc: "Yksinkertaiset arkipäivän keskustelut",
    levelB1: "Keskitaso",
    levelB1Desc: "Selkeä kommunikaatio tutuista aiheista",
    levelB2: "Ylempi keskitaso",
    levelB2Desc: "Luottava argumentointi ja keskustelut",
    accessibility: "Saavutettavuus",
    highContrastMode: "Korkean Kontrastin Tila",
    accessibilityDescription: "Säädä saavutettavuusasetuksia parantaaksesi käyttökokemustasi.",
    faqDescription: "Usein kysytyt kysymykset sovelluksen toiminnasta.",
    faqHowItWorks: "Miten sovellus toimii?",
    faqHowItWorksAnswer: "Sovellus käyttää tekoälyä keskustellakseen kanssasi norjaksi. Valitset CEFR-tasosi (A1-B2), ja ohjaaja mukauttaa kysymykset ja palautteen tasoosi. Harjoittelet vastaamalla norjaksi, ja ohjaaja antaa korjauksia ja selityksiä.",
    faqProgress: "Miten edistymiseni lasketaan?",
    faqProgressAnswer: "Edistymisesi lasketaan vastaustesi laadun perusteella. Tekoäly arvioi sujuvuutesi, sanavarastosi, kielioppisi ja johdonmukaisuutesi. Edistyminen voi nousta tai laskea suorituksesi mukaan, ja näet nykyisen tasosi edistymispalkissa.",
    faqCEFR: "Mitä ovat CEFR-tasot?",
    faqCEFRAnswer: "CEFR (Common European Framework of Reference) on kansainvälinen standardi kielitaidolle. A1 on aloittelija, A2 on alkeet, ja B1-B2 ovat keskitasoja. Voit muuttaa tasoasi milloin tahansa tasonvalintasivulta.",
    faqChangeLevel: "Miten voin vaihtaa tasoani?",
    faqChangeLevelAnswer: "Napsauta 'Vaihda Tasoa' -painiketta otsikossa tai käytä takaisin-painiketta palataksesi tasonvalintasivulle. Valitse uusi taso aloittaaksesi uuden keskustelun kyseisellä tasolla.",
    faqLanguage: "Voinko vaihtaa käyttöliittymän kieltä?",
    faqLanguageAnswer: "Kyllä! Voit vaihtaa käyttöliittymän kieltä asetuksista. Huomaa, että kielen vaihtaminen nollaa kaikki keskustelusi ja edistymisesi, koska ohjaaja mukautuu valitsemaasi kieleen.",
    faqSaveProgress: "Miten tallennan edistymiseni?",
    faqSaveProgressAnswer: "Rekisteröidy ilmaiselle tilille synkronoidaksesi edistymisesi laitteiden välillä. Ilman tiliä edistymisesi tallennetaan paikallisesti selaimeesi.",
    // Dashboard page translations
    dashboard: "Hallintapaneeli",
    welcomeBack: "Tervetuloa takaisin, {name}",
    dashboardSubtitle: "Tervetuloa NorskTutorin kieltenoppimisen hallintapaneeliin.",
    progressionBannerLevelUp:
      "You're progressing — ready to try {level}? You can change level anytime.",
    progressionBannerLevelDown:
      "This level looks challenging — try {level} for more support?",
    progressionBannerExercise:
      "Try a focused exercise from Writing to break through a plateau.",
    progressionReviewLevels: "Review levels",
    progressionDismiss: "Dismiss",
        writing: "Kirjoittaminen",
    writingDesc: "Harjoittele kirjoittamista ja paranna kielioppiasi interaktiivisen ohjaajamme avulla.",
    findTutor: "Etsi ohjaaja",
    findTutorDesc: "Ota yhteyttä äidinkielisiin puhujiin ja ammattitaitoisiin opettajiin yksityistunneille.",
      startChat: "Aloita chat",
    browseTutors: "Selaa ohjaajia",
      footerCopyright: "Norsk Tutor © 2026. Tehty ❤️:lla oppimista varten.",
    // Tutors page translations
    findNorwegianTutor: "Etsi norjan ohjaaja",
    bookLessons: "Varaa yksityistunteja äidinkielisten puhujien ja sertifioitujen opettajien kanssa.",
    searchPlaceholder: "Hae nimellä tai avainsanalla...",
    availability: "Saatavuus",
    price: "Hinta",
    moreFilters: "Lisää suodattimia",
    certifiedTeacher: "Sertifioitu opettaja",
    communityTutor: "Yhteisön ohjaaja",
    lessons: "oppitunnit",
    rate: "Hinta",
    bookTrial: "Varaa kokeilutunti",
    message: "Viesti",
    viewAllTutors: "Näytä kaikki 142 ohjaajaa",
    findTutors: "Etsi ohjaajia",
    tryAgain: "Yritä uudelleen",
    newExercise: "Uusi harjoitus",
    exerciseCorrectLabel: "oikein",
    selectExerciseToBegin: "Valitse harjoitustila yltä aloittaaksesi...",
    exerciseHowPractice: "Miten haluat harjoitella?",
    exerciseChooseModeSubtitle: "Valitse harjoitustila aloittaaksesi",
    exerciseChooseTopic: "Valitse aihe",
    exerciseChooseGrammar: "Valitse kielioppifokus",
    },
  pl: {
    welcomeTitle: "Witamy w nauce norweskiego!",
    selectLevelSubtitle: "Wybierz swój obecny poziom CEFR, aby rozpocząć",
    currentLevelSubtitle:
      "Twój obecny poziom: {level}. Wybierz nowy poziom, aby zmienić.",
    selectNewLevel: "Wybierz nowy poziom",
    selectLanguage: "Wybierz język",
    languageSelectionTitle: "Welcome to Norwegian Learning!",
    languageSelectionSubtitle: "Please select your preferred language",
    appTitle: "Nauka Norweskiego",
    greeting: "Cześć!",
    greetingSubtitle: "Jak mogę Ci pomóc w nauce norweskiego dzisiaj?",
    placeholder: "Napisz tutaj po norwesku...",
    changeLevel: "Zmień Poziom",
    disclaimer: "Nauka Norweskiego może wyświetlać niedokładne informacje, proszę weryfikować odpowiedzi.",
    progress: "Postęp",
    newChat: "Nowa Rozmowa",
    conversations: "Rozmowy",
    help: "Pomoc",
    history: "Historia",
    settings: "Ustawienia",
    you: "Ty",
    tutor: "Tutor",
    theme: "Motyw",
    systemMode: "System",
    lightMode: "Jasny",
    darkMode: "Ciemny",
    language: "Język",
    languageDescription: "Wybierz preferowany język interfejsu.",
    helpCenter: "Centrum Pomocy",
    privacy: "Prywatność",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Wyjaśnij zasadę V2",
    suggestionGrammar: "Pomóż mi z gramatyką",
    suggestionTask: "Daj mi zadanie",
    jumpToBottom: "Przejdź na dół",
    back: "Wstecz",
    errorTitle: "Coś poszło nie tak",
    errorMessage: "Proszę odświeżyć stronę lub spróbować ponownie później.",
    refresh: "Odśwież stronę",
    syncing: "Synchronizowanie...",
    syncError: "Błąd synchronizacji",
    pendingChanges: "oczekujące zmiany",
    login: "Zaloguj się",
    signupForFree: "Zarejestruj się za darmo",
    authNudgeTitle: "Save your progress across devices",
    authNudgeBody:
      "Create a free account to sync your conversations. You can keep chatting without signing in.",
    authNudgeSignIn: "Sign in",
    authNudgeDismiss: "Not now",
    account: "Konto",
    changeLanguage: "Zmień język",
    changeLanguageWarning: "Zmiana języka usunie wszystkie Twoje rozmowy i zresetuje Twój postęp. Tej akcji nie można cofnąć. Czy chcesz kontynuować?",
    confirm: "Kontynuuj",
    cancel: "Anuluj",
    levelA1: "Początkujący",
    levelA1Desc: "Podstawowe zwroty i wprowadzenia",
    levelA2: "Elementarny",
    levelA2Desc: "Proste codzienne rozmowy",
    levelB1: "Średniozaawansowany",
    levelB1Desc: "Jasna komunikacja na znane tematy",
    levelB2: "Wyższy średniozaawansowany",
    levelB2Desc: "Pewne argumentowanie i dyskusje",
    accessibility: "Dostępność",
    highContrastMode: "Tryb Wysokiego Kontrastu",
    accessibilityDescription: "Dostosuj ustawienia dostępności, aby poprawić swoje doświadczenie.",
    faqDescription: "Często zadawane pytania dotyczące działania aplikacji.",
    faqHowItWorks: "Jak działa aplikacja?",
    faqHowItWorksAnswer: "Aplikacja wykorzystuje AI do prowadzenia rozmów z Tobą po norwesku. Wybierasz swój poziom CEFR (A1-B2), a korepetytor dostosowuje pytania i informacje zwrotne do Twojego poziomu. Ćwiczysz, odpowiadając po norwesku, a korepetytor zapewnia poprawki i wyjaśnienia.",
    faqProgress: "Jak obliczany jest mój postęp?",
    faqProgressAnswer: "Twój postęp jest obliczany na podstawie jakości Twoich odpowiedzi. AI ocenia Twoją płynność, słownictwo, gramatykę i spójność. Postęp może wzrosnąć lub spaść w zależności od Twojej wydajności, a swój aktualny poziom zobaczysz na pasku postępu.",
    faqCEFR: "Czym są poziomy CEFR?",
    faqCEFRAnswer: "CEFR (Common European Framework of Reference) to międzynarodowy standard dla biegłości językowej. A1 to początkujący, A2 to elementarny, i B1-B2 to poziomy średniozaawansowane. Możesz zmienić swój poziom w dowolnym momencie na stronie wyboru poziomu.",
    faqChangeLevel: "Jak zmienić mój poziom?",
    faqChangeLevelAnswer: "Kliknij przycisk 'Zmień Poziom' w nagłówku lub użyj przycisku Wstecz, aby wrócić do strony wyboru poziomu. Wybierz nowy poziom, aby rozpocząć nową rozmowę na tym poziomie.",
    faqLanguage: "Czy mogę zmienić język interfejsu?",
    faqLanguageAnswer: "Tak! Możesz zmienić język interfejsu w Ustawieniach. Pamiętaj, że zmiana języka zresetuje wszystkie Twoje rozmowy i postęp, ponieważ korepetytor dostosowuje się do wybranego języka.",
    faqSaveProgress: "Jak zapisać mój postęp?",
    faqSaveProgressAnswer: "Zarejestruj się, aby uzyskać bezpłatne konto, aby synchronizować swój postęp na wszystkich urządzeniach. Bez konta Twój postęp jest przechowywany lokalnie w przeglądarce.",
    // Dashboard page translations
    dashboard: "Panel",
    welcomeBack: "Witaj ponownie, {name}",
    dashboardSubtitle: "Witaj w panelu nauki języków NorskTutor.",
    progressionBannerLevelUp:
      "You're progressing — ready to try {level}? You can change level anytime.",
    progressionBannerLevelDown:
      "This level looks challenging — try {level} for more support?",
    progressionBannerExercise:
      "Try a focused exercise from Writing to break through a plateau.",
    progressionReviewLevels: "Review levels",
    progressionDismiss: "Dismiss",
        writing: "Pisanie",
    writingDesc: "Ćwicz pisanie i popraw swoją gramatykę z naszym interaktywnym korepetytorem.",
    findTutor: "Znajdź korepetytora",
    findTutorDesc: "Połącz się z native speakerami i profesjonalnymi nauczycielami na lekcje 1 na 1.",
      startChat: "Rozpocznij czat",
    browseTutors: "Przeglądaj korepetytorów",
      footerCopyright: "Norsk Tutor © 2026. Stworzone z ❤️ do nauki.",
    // Tutors page translations
    findNorwegianTutor: "Znajdź korepetytora norweskiego",
    bookLessons: "Zarezerwuj lekcje 1 na 1 z native speakerami i certyfikowanymi nauczycielami.",
    searchPlaceholder: "Szukaj po nazwie lub słowie kluczowym...",
    availability: "Dostępność",
    price: "Cena",
    moreFilters: "Więcej filtrów",
    certifiedTeacher: "Certyfikowany nauczyciel",
    communityTutor: "Korepetytor społeczności",
    lessons: "lekcje",
    rate: "Stawka",
    bookTrial: "Zarezerwuj lekcję próbną",
    message: "Wiadomość",
    viewAllTutors: "Zobacz wszystkich 142 korepetytorów",
    findTutors: "Znajdź korepetytorów",
    tryAgain: "Spróbuj ponownie",
    newExercise: "Nowe ćwiczenie",
    exerciseCorrectLabel: "poprawnie",
    selectExerciseToBegin: "Wybierz tryb ćwiczenia powyżej, aby rozpocząć...",
    exerciseHowPractice: "Jak chcesz ćwiczyć?",
    exerciseChooseModeSubtitle: "Wybierz tryb ćwiczenia, aby rozpocząć",
    exerciseChooseTopic: "Wybierz temat",
    exerciseChooseGrammar: "Wybierz fokus gramatyczny",
    },
  uk: {
    welcomeTitle: "Ласкаво просимо до вивчення норвезької!",
    selectLevelSubtitle: "Виберіть свій поточний рівень CEFR, щоб розпочати",
    currentLevelSubtitle:
      "Ваш поточний рівень: {level}. Виберіть новий рівень, щоб змінити.",
    selectNewLevel: "Вибрати новий рівень",
    selectLanguage: "Вибрати мову",
    languageSelectionTitle: "Welcome to Norwegian Learning!",
    languageSelectionSubtitle: "Please select your preferred language",
    appTitle: "Вивчення Норвезької",
    greeting: "Привіт!",
    greetingSubtitle: "Як я можу допомогти вам вивчити норвезьку сьогодні?",
    placeholder: "Напишіть тут норвезькою...",
    changeLevel: "Змінити Рівень",
    disclaimer: "Вивчення норвезької може відображати неточну інформацію, будь ласка, перевіряйте відповіді.",
    progress: "Прогрес",
    newChat: "Нова Розмова",
    conversations: "Розмови",
    help: "Допомога",
    history: "Історія",
    settings: "Налаштування",
    you: "Ви",
    tutor: "Репетитор",
    theme: "Тема",
    systemMode: "Системний",
    lightMode: "Світлий",
    darkMode: "Темний",
    language: "Мова",
    languageDescription: "Виберіть бажану мову інтерфейсу.",
    helpCenter: "Довідковий центр",
    privacy: "Конфіденційність",
    suggestionStart: "Hei, jeg heter...",
    suggestionV2: "Поясніть правило V2",
    suggestionGrammar: "Допоможіть мені з граматикою",
    suggestionTask: "Дайте мені завдання",
    jumpToBottom: "Перейти донизу",
    back: "Назад",
    errorTitle: "Щось пішло не так",
    errorMessage: "Будь ласка, оновіть сторінку або спробуйте пізніше.",
    refresh: "Оновити сторінку",
    syncing: "Синхронізація...",
    syncError: "Помилка синхронізації",
    pendingChanges: "незавершені зміни",
    login: "Увійти",
    signupForFree: "Зареєструватися безкоштовно",
    authNudgeTitle: "Save your progress across devices",
    authNudgeBody:
      "Create a free account to sync your conversations. You can keep chatting without signing in.",
    authNudgeSignIn: "Sign in",
    authNudgeDismiss: "Not now",
    account: "Обліковий запис",
    changeLanguage: "Змінити мову",
    changeLanguageWarning: "Зміна мови видалить усі ваші розмови та скине ваш прогрес. Цю дію не можна скасувати. Бажаєте продовжити?",
    confirm: "Продовжити",
    cancel: "Скасувати",
    levelA1: "Початківець",
    levelA1Desc: "Базові фрази та вступ",
    levelA2: "Елементарний",
    levelA2Desc: "Прості щоденні розмови",
    levelB1: "Середній",
    levelB1Desc: "Чітке спілкування на знайомі теми",
    levelB2: "Вище середнього",
    levelB2Desc: "Впевнена аргументація та дискусії",
    accessibility: "Доступність",
    highContrastMode: "Режим Високого Контрасту",
    accessibilityDescription: "Налаштуйте параметри доступності, щоб покращити свій досвід.",
    faqDescription: "Часті запитання про те, як працює додаток.",
    faqHowItWorks: "Як працює додаток?",
    faqHowItWorksAnswer: "Додаток використовує ШІ для ведення розмов з вами норвезькою мовою. Ви обираєте свій рівень CEFR (A1-B2), і репетитор адаптує запитання та відгуки до вашого рівня. Ви практикуєтеся, відповідаючи норвезькою, а репетитор надає виправлення та пояснення.",
    faqProgress: "Як розраховується мій прогрес?",
    faqProgressAnswer: "Ваш прогрес розраховується на основі якості ваших відповідей. ШІ оцінює вашу вільність, словниковий запас, граматику та послідовність. Прогрес може зростати або зменшуватися залежно від вашої продуктивності, і ви побачите свій поточний рівень на панелі прогресу.",
    faqCEFR: "Що таке рівні CEFR?",
    faqCEFRAnswer: "CEFR (Common European Framework of Reference) – це міжнародний стандарт для володіння мовою. A1 – початківець, A2 – елементарний, і B1-B2 – середні рівні. Ви можете змінити свій рівень у будь-який час на сторінці вибору рівня.",
    faqChangeLevel: "Як змінити мій рівень?",
    faqChangeLevelAnswer: "Натисніть кнопку 'Змінити Рівень' у заголовку або скористайтеся кнопкою 'Назад', щоб повернутися на сторінку вибору рівня. Виберіть новий рівень, щоб розпочати нову розмову на цьому рівні.",
    faqLanguage: "Чи можу я змінити мову інтерфейсу?",
    faqLanguageAnswer: "Так! Ви можете змінити мову інтерфейсу в Налаштуваннях. Зверніть увагу, що зміна мови скине всі ваші розмови та ваш прогрес, оскільки репетитор адаптується до обраної вами мови.",
    faqSaveProgress: "Як зберегти мій прогрес?",
    faqSaveProgressAnswer: "Зареєструйтеся, щоб отримати безкоштовний обліковий запис, щоб синхронізувати свій прогрес на всіх пристроях. Без облікового запису ваш прогрес зберігається локально у вашому браузері.",
    // Dashboard page translations
    dashboard: "Панель",
    welcomeBack: "Ласкаво просимо, {name}",
    dashboardSubtitle: "Ласкаво просимо до панелі вивчення мов NorskTutor.",
    progressionBannerLevelUp:
      "You're progressing — ready to try {level}? You can change level anytime.",
    progressionBannerLevelDown:
      "This level looks challenging — try {level} for more support?",
    progressionBannerExercise:
      "Try a focused exercise from Writing to break through a plateau.",
    progressionReviewLevels: "Review levels",
    progressionDismiss: "Dismiss",
        writing: "Письмо",
    writingDesc: "Практикуйте письмо та покращуйте свою граматику за допомогою нашого інтерактивного репетитора.",
    findTutor: "Знайти репетитора",
    findTutorDesc: "Зв'яжіться з носіями мови та професійними викладачами для індивідуальних уроків.",
      startChat: "Почати чат",
    browseTutors: "Переглянути репетиторів",
      footerCopyright: "Norsk Tutor © 2026. Зроблено з ❤️ для навчання.",
    // Tutors page translations
    findNorwegianTutor: "Знайти репетитора норвезької мови",
    bookLessons: "Забронюйте індивідуальні уроки з носіями мови та сертифікованими викладачами.",
    searchPlaceholder: "Пошук за ім'ям або ключовим словом...",
    availability: "Доступність",
    price: "Ціна",
    moreFilters: "Більше фільтрів",
    certifiedTeacher: "Сертифікований викладач",
    communityTutor: "Репетитор спільноти",
    lessons: "уроки",
    rate: "Ставка",
    bookTrial: "Забронювати пробний урок",
    message: "Повідомлення",
    viewAllTutors: "Переглянути всіх 142 репетиторів",
    findTutors: "Знайти репетиторів",
    tryAgain: "Спробувати ще раз",
    newExercise: "Нова вправа",
    exerciseCorrectLabel: "правильно",
    selectExerciseToBegin: "Оберіть режим вправи вище, щоб почати...",
    exerciseHowPractice: "Як ви хочете практикуватися?",
    exerciseChooseModeSubtitle: "Оберіть режим вправи, щоб почати",
    exerciseChooseTopic: "Оберіть тему",
    exerciseChooseGrammar: "Оберіть граматичний фокус",
    },
};

export const isValidLanguageCode = (
  value: string,
): value is LanguageCode => SUPPORTED_LANGUAGES.some((lang) => lang.code === value);

// Cache for dynamically loaded translations
// let dynamicTranslationsCache: Map<LanguageCode, Translations> = new Map();

/**
 * Get translation with support for both static (current) and dynamic (future) loading
 * For now, uses static translations. In future, can switch to dynamic loading for code splitting.
 */
export const getTranslation = (
  language: LanguageCode,
  key: keyof Translations,
  params?: Record<string, string>,
): string => {
  // Try dynamic cache first (if available)
  // Dynamic loading disabled to ensure stability with static translations
  /*
  const cached = dynamicTranslationsCache.get(language);
  if (cached && cached[key]) {
    const translation = cached[key];
    if (!params) return translation;
    return Object.entries(params).reduce(
      (acc, [paramKey, paramValue]) => acc.replace(`{${paramKey}}`, paramValue),
      translation,
    );
  }
  */

  // Fallback to static translations (current implementation)
  const translation = translations[language]?.[key] ?? translations[DEFAULT_LANGUAGE]?.[key] ?? '';
  if (!params) return translation;
  return Object.entries(params).reduce(
    (acc, [paramKey, paramValue]) => acc.replace(`{${paramKey}}`, paramValue),
    translation,
  );
};

/**
 * Load and cache translations dynamically (for future use with code splitting)
 */
export const loadAndCacheTranslations = async (_language: LanguageCode): Promise<void> => {
  return; // Dynamic loading disabled
  /*
  if (dynamicTranslationsCache.has(language)) {
    return; // Already cached
  }

  try {
    // Try to load from JSON file (future implementation)
    const { loadTranslations } = await import('@/lib/i18n/loader');
    const loaded = await loadTranslations(language);
    dynamicTranslationsCache.set(language, loaded);
  } catch (error) {
    // Fallback to static translations if JSON file doesn't exist
    // Dynamic translations unavailable, using static fallback
    if (translations[language]) {
      dynamicTranslationsCache.set(language, translations[language]);
    }
  }
  */
};
